### ISSUE TITLE
Any version seems to have SQLite issue (SQLite is installed)

### ISSUE THREAD

**Issue by GiggleSquid** [bcssov/IronyModManager#130]
**Describe the bug**
I updated from a 1.5 version (cant remember which one)
After trying to execute on Linux : 
It throws an SQLitePCLRaw exception

The previous version I had (1.5 (not sure which one) worked fine)

**To Reproduce**
1. Execute linux version

**Logs**
Unhandled exception. System.InvalidOperationException: Dependency resolution failed for component /home/*irony_root*/linux-x64/IronyModManager.IO.dll with error code -2147450740. Detailed error: Error:
  An assembly specified in the application dependencies manifest (IronyModManager.IO.deps.json) was not found:
    package: 'SQLitePCLRaw.lib.e_sqlite3', version: '2.0.3'
    path: 'runtimes/linux-x64/native/libe_sqlite3.so'

   at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
   at IronyModManager.DI.Assemblies.SharedLoadContext..ctor(String assembly) in D:\Working\IronyModManager\src\IronyModManager.DI\Assemblies\SharedLoadContext.cs:line 58
   at IronyModManager.DI.Assemblies.AssemblyFinder.FindAndLoadAssemblies(AssemblyFinderParams finderParams) in D:\Working\IronyModManager\src\IronyModManager.DI\Assemblies\AssemblyFinder.cs:line 86
   at IronyModManager.DI.Assemblies.AssemblyFinder.Find(AssemblyFinderParams finderParams) in D:\Working\IronyModManager\src\IronyModManager.DI\Assemblies\AssemblyFinder.cs:line 47
   at IronyModManager.DI.Bootstrap.RegisterDIAssemblies(AssemblyFinderParams[] assemblyFinderParams) in D:\Working\IronyModManager\src\IronyModManager.DI\Bootstrap.cs:line 163
   at IronyModManager.DI.Bootstrap.RegisterAssemblies() in D:\Working\IronyModManager\src\IronyModManager.DI\Bootstrap.cs:line 131
   at IronyModManager.DI.Bootstrap.Setup(DIOptions opts) in D:\Working\IronyModManager\src\IronyModManager.DI\Bootstrap.cs:line 61
   at IronyModManager.Program.InitDI() in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 165
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 70
[1]    12779 abort (core dumped)  ./IronyModManager

**Version:**
 - OS: [Manjaro 5.8]
 - Irony Version [e.g. 1.5.48-latest] (afaik)

**Additional context**
As far as I can figure out myself, this may be a compile error. But I have very limited experience with this

**Comment by GiggleSquid** [comment]
> Not a compile error but a dependency resolving error. What happens if you try say a 1.6.x version?

Same error on every version I've tried. I will admit that I've used Linux for a while but I'm not sure how to interpenetrate certain  errors received. What is confusing me is the fact that the 1.5 version was fine, but every other has this same issue. I have tried to use an approximate 1.5 release but this results in the same issue.

Please let me know if you'd lime any more logs. I'm just kind of at a loss

**Comment by bcssov** [comment]
No need, I already know the reason. I'll release an update, seems going from v1.6 and going forward I messed up my publish procedures of including some dev files in the release. If you find any files named '*.deps.json' and delete them Irony should start up. I'll release a new version which resolves this as well.

**Comment by bcssov** [comment]
Acknowledged as a bug, is fixed in the upcoming release. What saddens me is that nobody reported this to me earlier so those poor souls who downloaded Irony >= v1.6 could not get it to boot up for them on Linux. On my end that large v1.6 update caused a lot of reshuffling and changes so this fell through the cracks. Thanks for the report.

**Comment by GiggleSquid** [comment]
Awesome! Thanks for the very quick fix!
Sorry I took so long to replay, but can confirm all working again
