### ISSUE TITLE
Crash opening conflict solver

### ISSUE THREAD

**Issue by skwerlman** [bcssov/IronyModManager#134]
**Describe the bug**
When opening the conflict solver, IMM crashes with an IndexOutOfRangeException

**To Reproduce**
1. Load the conflict solver
2. It crashes (on occasion!) at the start of step 3

**Expected behavior**
The conflict solver should load every time

**Screenshots**
N/A

**Logs**
```
2020-10-24 18:44:22.7982|ERROR|IronyModManager.Log.Logger|ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at IronyModManager.IO.Mods.ModPatchExporter.<>c__DisplayClass28_0.<<GetPatchStateInternalAsync>g__loadCode|0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModPatchExporter.cs:line 630
--- End of stack trace from previous location where exception was thrown ---
   at IronyModManager.IO.Mods.ModPatchExporter.GetPatchStateInternalAsync(ModPatchExporterParameters parameters, Boolean loadExternalCode) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModPatchExporter.cs:line 646
   at IronyModManager.IO.Mods.ModPatchExporter.GetPatchStateAsync(ModPatchExporterParameters parameters, Boolean loadExternalCode) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModPatchExporter.cs:line 258
   at IronyModManager.Services.ModPatchCollectionService.SyncPatchStateAsync(IConflictResult conflictResult, String collectionName) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 876
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass113_0.<<AnalyzeModsAsync>b__2>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 387
--- End of stack trace from previous location where exception was thrown ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(PatchStateMode mode) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 385
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass118_0.<<OnActivated>b__16>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 569
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 254
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler s, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__10_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 577
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 81
```

**Version:**
 - OS: Arch Linux 5.9.1-zen2
 - Irony Version: 1.7.53

**Additional context**
The conflict solver loads correctly almost all of the time (i've only had it crash once out of ~25 loads)

**Comment by bcssov** [comment]
Luckily it's a simple threading issue. Forgot to switch to a thread safe collection when I rewrote this logic a bunch of times. Weird that it wasn't reported sooner though.
