### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by JokerVagus** [bcssov/IronyModManager#167]
**Describe the bug**
When I use the conflict resolver, default or advanced, it will cause a fatal error to occur and close the program.

**To Reproduce**
1. Open Irony Mod Manager
2. Click on Conflict Solver
3. Click either Advanced or Default
4. Wait for it to do its process

**Expected behavior**
I expected it to just run and alter the mod load order and not close when finished.

**Screenshots**
![dwkiujhgetr](https://user-images.githubusercontent.com/62265899/102683138-62979a80-4194-11eb-9f9c-9d23bdca67b8.PNG)

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Windows 10 Pro
 - Irony Version: v1.10.58

**Additional context**
N/A

**Comment by ErenForce** [comment]
Op didn't both spending 2 minutes investigating before submitting the issue. The error is with Ethics and Civics Classic 2.8, there's some weird `UnauthorizedAccessException` to the base_collection folder during the call from `WriteAllTextAsync` and during `ValidateFileHandle`.

I verified permissions 10 times and verified that without this mod the Conflict Solver works. Unpacking the zip in the mod directory didn't seem to help nor running the application in administrator. I can only conclude that there's a lock on the file, perhaps from an improperly handled disposable keeping the file "open".

**Comment by MemedHams** [comment]
Hi, I'm having the same issue- where can I find the logs so I can figure out which mod is causing this? I don't have Ethics and Civics Classic 2.8.

**Comment by MemedHams** [comment]
On further examination, I managed to figure out that Primitive worlds 2.7 was contributing to the issue, but the manager's still crashing on sort even after I took it out.

**Comment by bcssov** [comment]
I don't think I need to mention that I clearly cannot reproduce such an issue so to reply in order:

@JokerVagus Logs or otherwise I cannot help you. As mentioned you spent less than 2 minutes on reporting this issue giving me no information whatsoever. 
@ ErenForce I need correct logs to see which piece of code threw an error. There's thousands of lines of code here. UnauthorizedAccessException usually means Irony does not have read\write permissions and usually means in this context of most likely means that an aggressive AV setting is denying Irony permissions to either the Stellaris mod folder or it's app settings folder.
@MemedHams See the homepage to find where the logs are located: https://bcssov.github.io/IronyModManager/
If you're seeing UnauthorizedAccessException as well this means an aggressive AV setting denying Irony permissions.

**Comment by MemedHams** [comment]
> 2020-12-19 10:04:20.8184 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.yModManager\Program.cs:line 84

I couldn't find any offending data in the full log for any specific mod, but this is the basic error message

**Comment by bcssov** [comment]
Google Github markdown cheat sheet, if there is one you'll find it there. Alternatively upload a txt file as an attachment. Anyways the log snippet is actually unhelpful, it just tells me that Reactive pipeline was broken due to an exception somewhere down the pipeline.

**Comment by MemedHams** [comment]
# log(not made of wood)
<details>
  <summary>expand for full log</summary>
  2020-12-19 10:04:20.8184 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.AggregateException: One or more errors occurred. (Length cannot be less than zero. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at IronyModManager.Parser.Generic.LocalizationParser.Parse(ParserArgs args) in D:\Working\IronyModManager\src\IronyModManager.Parser\Generic\LocalizationParser.cs:line 136
   at IronyModManager.Parser.ParserManager.InvokeParsers(ParserManagerArgs args) in D:\Working\IronyModManager\src\IronyModManager.Parser\ParserManager.cs:line 292
   at IronyModManager.Services.ModPatchCollectionService.ParseModFiles(IGame game, IEnumerable`1 fileInfos, IModObject modObject) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 1796
   at IronyModManager.Services.ModPatchCollectionService.<>c__DisplayClass16_0.<GetModObjectsAsync>b__0(IMod m) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 512
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at IronyModManager.Services.ModPatchCollectionService.GetModObjectsAsync(IGame game, IEnumerable`1 mods, String collectionName) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 509
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass116_0.<<AnalyzeModsAsync>b__0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 397
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(Int64 id, PatchStateMode mode) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 395
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass121_0.<<OnActivated>b__22>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 710
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__10_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 84 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.AggregateException: One or more errors occurred. (Length cannot be less than zero. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at IronyModManager.Parser.Generic.LocalizationParser.Parse(ParserArgs args) in D:\Working\IronyModManager\src\IronyModManager.Parser\Generic\LocalizationParser.cs:line 136
   at IronyModManager.Parser.ParserManager.InvokeParsers(ParserManagerArgs args) in D:\Working\IronyModManager\src\IronyModManager.Parser\ParserManager.cs:line 292
   at IronyModManager.Services.ModPatchCollectionService.ParseModFiles(IGame game, IEnumerable`1 fileInfos, IModObject modObject) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 1796
   at IronyModManager.Services.ModPatchCollectionService.<>c__DisplayClass16_0.<GetModObjectsAsync>b__0(IMod m) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 512
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at IronyModManager.Services.ModPatchCollectionService.GetModObjectsAsync(IGame game, IEnumerable`1 mods, String collectionName) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 509
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass116_0.<<AnalyzeModsAsync>b__0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 397
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(Int64 id, PatchStateMode mode) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 395
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass121_0.<<OnActivated>b__22>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 710
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__10_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass2_1`1.<Schedule>b__1()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 84
</details>

**Comment by bcssov** [comment]
Cannot reproduce, the exception happening should not be happening (but somehow it is). Acording to the log substring querying crashes because Irony is attempting to access a non zero based string index in a localization file (yml file):
https://github.com/bcssov/IronyModManager/blob/3d848e3bbc3f1d2f56c11794fcde89d1cf0cab3a/src/IronyModManager.Parser/Generic/LocalizationParser.cs#L136
However a few lines above there is a failsafe which checks whether the index is greater than zero: https://github.com/bcssov/IronyModManager/blob/3d848e3bbc3f1d2f56c11794fcde89d1cf0cab3a/src/IronyModManager.Parser/Generic/LocalizationParser.cs#L133-L136

And just by an off chance that there's something in the mods you mentioned I tried running them on my own machine, no errors no crashes. Try reinstalling Irony in a clean folder or delete everything from the previous Irony installation and copy these new files again. I've tried the Primitive World 2.7 and Ethics and Civics Classic and I've noticed no problems on my end.

**Comment by MemedHams** [comment]
huh. I'll reinstall and check it out.

**Comment by MemedHams** [comment]
still happening, unfortunately. What version of the launcher are you running?

**Comment by bcssov** [comment]
I always run the latest version in the debugger. In this case that would be 1.10.60 which is as of this moment unreleased with 2 small changes unrelated to the issue at hand.

How about your actually share your system info, locale version that you're using and a small mod list that reproduces the issue. The mod list should contain 2-3 mods at most.

**Comment by ErenForce** [comment]
For some reason Avast didn't bother asking if the manager should be blocked it just went ahead and blocked it. After running it for the 20th time the popup showed. Allowing it access also fixed sqlite saying the database was readonly.
