### ISSUE TITLE
Fatal Exception when using Conflict Solver->Default

### ISSUE THREAD

**Issue by Karamethien** [bcssov/IronyModManager#198]
It does this each time.  According to the log it is some sort of file access error.

It seems to crash for Merging Mods as well, but I think that is because conflict resolver crashed.

I am running Stellaris 2.8.1 and Irony Manager 1.11.33

[2021-02-12_Error.log](https://github.com/bcssov/IronyModManager/files/5970473/2021-02-12_Error.log)

2021-02-12 00:25:23.0744 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.AggregateException: Retry strategy failed. (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.) (Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'D:\Win7 Users\JamesX\Documents\Paradox Interactive\Stellaris\mod\IronyModManager_Main\common\section_templates\!!!_ec4d0033$ORGANIC$_$CORE_JUGGERNAUT_SECTION$.txt' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.AsyncStreamWriter(String path, Encoding encoding, Boolean append)
   at System.IO.File.WriteAllTextAsync(String path, String contents, Encoding encoding, CancellationToken cancellationToken)
   at IronyModManager.IO.Mods.ModPatchExporter.<>c__DisplayClass33_3.<<WriteMergedContentAsync>b__6>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModPatchExporter.cs:line 848
--- End of stack trace from previous location ---

**Comment by bcssov** [comment]
Looks like an AV is blocking Irony.

**Comment by Karamethien** [comment]
Thanks, It seems adding the program to Avast Anti-Virus Exception worked.  Much appreciated.
