### ISSUE TITLE
File Already Exists error - Likely linked to a WebClient OpenSSL decryptyion error

### ISSUE THREAD

**Issue by EisbarGFX** [bcssov/IronyModManager#235]
**Describe the bug**
When installing the new update for the mod manager, 1.15.18, the mod manager crashes with a file already exists error.

**To Reproduce**
1. Launch an old version of Irony via ./IronyModManager terminal command
2. Go to Options -> Install Updates
3. Wait for update to download
4. Receive a crash to terminal 

**Expected behavior**
I would expect the update to finish smoothly with no crashes or errors.

**Screenshots**
[Error box appears during update process](https://user-images.githubusercontent.com/38171736/115179562-7393e200-a088-11eb-8757-624796c4fe91.png)

**Logs**
```
2021-04-18 20:52:43.9648|ERROR|IronyModManager.Log.Logger|System.IO.IOException: The file '/home/eisbar/.config/Mario/IronyModManager-Updater/89739c80-9efa-11eb-8d9d-19887da17861' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
   at IronyModManager.IO.Updater.Unpacker.UnpackUpdateAsync(String path) in D:\Working\IronyModManager\src\IronyModManager.IO\Updater\Unpacker.cs:line 82
   at IronyModManager.Implementation.Updater.IronySparkleUpdater.<>c__DisplayClass12_0.<<RunDownloadedInstaller>b__0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\Implementation\Updater\IronySparkleUpdater.cs:line 103
--- End of stack trace from previous location ---
   at IronyModManager.Implementation.Updater.IronySparkleUpdater.RunDownloadedInstaller(String downloadFilePath) in D:\Working\IronyModManager\src\IronyModManager\Implementation\Updater\IronySparkleUpdater.cs:line 103
   at NetSparkleUpdater.SparkleUpdater.InstallUpdate(AppCastItem item, String installPath)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at IronyModManager.Platform.x11.X11PlatformThreading.CheckSignaled() in D:\Working\IronyModManager\src\IronyModManager.Platform\x11\X11PlatformThreading.cs:line 371
   at IronyModManager.Platform.x11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in D:\Working\IronyModManager\src\IronyModManager.Platform\x11\X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 84
```

**Version:**
 - OS: Manjaro Linux 5.10.26-1
 - Irony Version: 1.10.58

**Additional context**
Probably related to an error that occurs earlier in the installation process, but goes away and the initial update succeeds if you retry it once or twice - Updating fails anywhere from 10-50% done with the following error:
```
2021-04-18 20:59:54.0044|ERROR|IronyModManager.Log.Logger|System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> Interop+OpenSsl+SslException: Decrypt failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.Decrypt(SafeSslHandle context, Byte[] outBuffer, Int32 offset, Int32 count, SslErrorCode& errorCode)
   at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
2021-04-18 20:59:57.2069|ERROR|IronyModManager.Log.Logger|System.Net.WebException: An exception occurred during a WebClient request.
 ---> System.IO.IOException: The decryption operation failed, see inner exception.
 ---> Interop+OpenSsl+SslException: Decrypt failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.Decrypt(SafeSslHandle context, Byte[] outBuffer, Int32 offset, Int32 count, SslErrorCode& errorCode)
   at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
   --- End of inner exception stack trace ---
```

**Comment by bcssov** [comment]
It seems like you updated from a < 1.11.30 version which has a known issue and was fixed (aka you needed to manually update). See https://github.com/bcssov/IronyModManager/discussions/192
