### ISSUE TITLE
Locked file Crash

### ISSUE THREAD

**Issue by bcssov** [bcssov/IronyModManager#24]
Mod file
```archive="J:/SteamLibrary/steamapps/workshop/content/281990/1170859543/realspace_beautifuluniverse.zip"
name="32 Real Space - Beautiful Universe v2.0 Patch"
picture="realspace_beautifuluniverse.jpg"
tags={
    "Real Space"
    "Graphics"
    "Patch"
}
supported_version="1.8.*
```
Log
```2020-04-15 15:04:54.5832 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The process cannot access the file 'C:\Users\tsimo\Documents\Paradox Interactive\Stellaris\mod\ugc_.mod' because it is being used by another process.)
 ---> System.IO.IOException: The process cannot access the file 'C:\Users\tsimo\Documents\Paradox Interactive\Stellaris\mod\ugc_.mod' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at IronyModManager.IO.Mods.ModWriter.WriteDescriptorAsync(ModWriterParameters parameters)
   at IronyModManager.Services.ModService.InstallModsAsync()
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 212
   --- End of inner exception stack trace --- System.IO.IOException: The process cannot access the file 'C:\Users\tsimo\Documents\Paradox Interactive\Stellaris\mod\ugc_.mod' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at IronyModManager.IO.Mods.ModWriter.WriteDescriptorAsync(ModWriterParameters parameters)
   at IronyModManager.Services.ModService.InstallModsAsync()
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 212
2020-04-15 15:04:54.6535 System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess()
   at Avalonia.AvaloniaObject..ctor()
   at Avalonia.StyledElement..ctor()
   at Avalonia.Visual..ctor()
   at Avalonia.Controls.ContentControl..ctor()
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor(Style style)
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at IronyModManager.MessageBoxes.GetFatalErrorWindow(String title, String header, String message) in D:\Working\IronyModManager\src\IronyModManager\Implementation\MessageBox.cs:line 50
   at IronyModManager.Program.LogError(Exception e) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 144
   at IronyModManager.Program.TaskScheduler_UnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs e) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 158
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize() System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess()
   at Avalonia.AvaloniaObject..ctor()
   at Avalonia.StyledElement..ctor()
   at Avalonia.Visual..ctor()
   at Avalonia.Controls.ContentControl..ctor()
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor(Style style)
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at IronyModManager.MessageBoxes.GetFatalErrorWindow(String title, String header, String message) in D:\Working\IronyModManager\src\IronyModManager\Implementation\MessageBox.cs:line 50
   at IronyModManager.Program.LogError(Exception e) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 144
   at IronyModManager.Program.TaskScheduler_UnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs e) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 158
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
˙˙˙

**Comment by bcssov** [comment]
Seems like it was Irony locking itself out due to async nature of the code. This can happen if a steam file doesn't have remote_file_id in descriptor. Need to workaround this by detecting folder which has an id as well to detect the steam id of the file.
