### ISSUE TITLE
Irony Mod Manager's Conflict Solver crashes

### ISSUE THREAD

**Issue by preveyj** [bcssov/IronyModManager#301]
**Describe the bug**
Irony Mod Manager crashes when trying to use the Conflict Solver.

**To Reproduce**
1. Load Irony Mod Manager
2. Click "Conflict Solver"
3. Select either Default or Advanced

**Expected behavior**
Open the conflict solver for Advanced mode, or complete the Default conflict solver to complete successfully.

**Screenshots**
![Irony mod manager error](https://user-images.githubusercontent.com/987821/135772274-0b370012-14d0-4df9-ab35-a429ad75cf77.png)

**Logs**
I don't know where Irony writes its logs to, and I will attach those logs to this issue once I do find them.

**Version:**
 - OS: Windows 10 Pro
 - Irony Version: 1.18.90

**Comment by bcssov** [comment]
I need logs. Wiki and the site provide location information.

**Comment by preveyj** [comment]
I've reproduced the error and added an error log here:
[2021-10-03_Error.log](https://github.com/bcssov/IronyModManager/files/7275334/2021-10-03_Error.log)

**Comment by preveyj** [comment]
2021-10-03 21:39:46.4627 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.Services.ModBaseService.PopulateModPath(IEnumerable`1 definitions, IEnumerable`1 collectionMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 884
   at IronyModManager.Services.ModPatchCollectionService.InitializePatchStateAsync(IConflictResult conflictResult, String collectionName) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 993
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass125_0.<<AnalyzeModsAsync>b__5>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 497
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(Int64 id, PatchStateMode mode, IEnumerable`1 versions) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 495
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass130_0.<<OnActivated>b__24>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 844
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 73
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__10_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 265
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 194
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 94 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.Services.ModBaseService.PopulateModPath(IEnumerable`1 definitions, IEnumerable`1 collectionMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 884
   at IronyModManager.Services.ModPatchCollectionService.InitializePatchStateAsync(IConflictResult conflictResult, String collectionName) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 993
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass125_0.<<AnalyzeModsAsync>b__5>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 497
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(Int64 id, PatchStateMode mode, IEnumerable`1 versions) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 495
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass130_0.<<OnActivated>b__24>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 844
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 73
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__10_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 573
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 265
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 194
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 94

**Comment by bcssov** [comment]
You seem to have a mod in your mod collection which does not have a name specified which is causing the crashing. This is a scenario which does not happen in a real world unless something goes really wrong.
