### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by VanquilKnight** [bcssov/IronyModManager#306]
Good day, I have encountered an error that whenever I start up the mod manager an error pop up appears and immediately shuts down ever since I tried the compress merge function.

1. Use Irony Mod Manager in Windows
2. Compress Merge

**Expected behavior**
After merge, all mods and collection should be functional, and testing ingame would result in less lag in the species tab.

**Logs**
Here's the information of the error pop up for your perusal.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Access to the path 'F:\System Volume Information' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'F:\System Volume Information' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at IronyModManager.Services.ModService.GetAllModDescriptors(String path, ModSource modSource) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 741
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 374
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace ---

Here are the logs from the IronModManager-Logs
[2021-11-05_Error.log](https://github.com/bcssov/IronyModManager/files/7476962/2021-11-05_Error.log)

[2021-11-05_Fatal.log](https://github.com/bcssov/IronyModManager/files/7476963/2021-11-05_Fatal.log)

**Version:**
 - OS: Windows 10
 - Irony Version: v1.19.76

Additional context:
I have 156 mods that are checked, with a total of 225 mods installed. A friend recommended me in using Merge Compress to solve a lag issue with the Species Tab.

**Comment by bcssov** [comment]
You pointed irony previously towards F drive and now it seems it's been dismounted or removed. Does this drive even exist on your computer?

**Comment by VanquilKnight** [comment]
> You pointed irony previously towards F drive and now it seems it's been dismounted or removed. Does this drive even exist on your computer?

Yes it is. That is my 2nd local disk that I store majority of my game data files, including Steam and Stellaris with it.

**Comment by bcssov** [comment]
Go to %appdata%\mario\ironymodmanager and paste Database_19.json here. You might want to open this file and rename some personal paths before you post it here for privacy reasons if you're worried. Leave the F drive specific data in though (like F:\\my path\\[renamed piece]\\stellaris.exe)

**Comment by VanquilKnight** [comment]
I honestly dont mind, here is the json file.
[Database_1.19.zip](https://github.com/bcssov/IronyModManager/files/7482005/Database_1.19.zip)

**Comment by bcssov** [comment]
Here's your problem you pointed Irony towards root F drive (set as custom directory) and Irony does not have permissions to read\write to this root drive. Here's the fixed file, replace it with the one you have at the same location. I've just removed the root F drive as custom mod directory. Running Irony as admin would have probably fixed the problem but you should **never** point any program towards a root of the drive.

[Database_1.19.zip](https://github.com/bcssov/IronyModManager/files/7486644/Database_1.19.zip)

**Comment by VanquilKnight** [comment]
> Here's your problem you pointed Irony towards root F drive (set as custom directory) and Irony does not have permissions to read\write to this root drive. Here's the fixed file, replace it with the one you have at the same location. I've just removed the root F drive as custom mod directory. Running Irony as admin would have probably fixed the problem but you should **never** point any program towards a root of the drive.
> 
> [Database_1.19.zip](https://github.com/bcssov/IronyModManager/files/7486644/Database_1.19.zip)

Ah I see, gotcha. Ill update you shortly on what's the result.

**Comment by VanquilKnight** [comment]
That solved it. Thanks for the help man. Appreciate the work you're doing.
