### ISSUE TITLE
Update error loop

### ISSUE THREAD

**Issue by Hawkknyght** [bcssov/IronyModManager#308]
**Describe the bug**
user error when updating with virus protection causing loop unable to update

**To Reproduce**
1. Start Irony
2. Update Irony
3. forget to shut off virus protection
4. shut off virus protection
5. restart Irony
6. update Irony and get crash loop

**Expected behavior**
Would like to be able to update Irony and get out of the loop without having to reinstall Irony

**Screenshots**

**Logs**
"System.UnauthorizedAccessException: Access to the path 'win-x64-setup.exe' is denied."
   "at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)"
   "at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)"
   "at IronyModManager.IO.Common.DiskOperations.DeleteDirectory(String directory, Boolean recursive) in" "D:\Working\IronyModManager\src\IronyModManager.IO.Common\DiskOperations.cs:line 40"
   "at IronyModManager.IO.Updater.Unpacker.UnpackUpdateAsync(String path) in" "D:\Working\IronyModManager\src\IronyModManager.IO\Updater\Unpacker.cs:line 75"
   "at IronyModManager.Implementation.Updater.IronySparkleUpdater.<>c__DisplayClass12_0."<<RunDownloadedInstaller>b__0>d.MoveNext() in" "D:\Working\IronyModManager\src\IronyModManager\Implementation\Updater\IronySparkleUpdater.cs:line 104"
"--- End of stack trace from previous location ---"
   "at IronyModManager.Implementation.Updater.IronySparkleUpdater.RunDownloadedInstaller(String downloadFilePath) in" "D:\Working\IronyModManager\src\IronyModManager\Implementation\Updater\IronySparkleUpdater.cs:line 104"
   "at NetSparkleUpdater.SparkleUpdater.InstallUpdate(AppCastItem item, String installPath)"
   "at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)"
"   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in" "/_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33"
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in "/_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 278"
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in "/_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205"
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in "/_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61"
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in "/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126"
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in "/_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175"
  " at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 96"

**Version:**
 - OS: [Windows]
 - Irony Version [one prior to latest]

**Additional context**

**Comment by bcssov** [comment]
This is an updater unpacking error, basically Irony was denied permission to create a folder. Install irony manually I guess.
