### ISSUE TITLE
Can't run irony mod manager

### ISSUE THREAD

**Issue by hosunggoon** [bcssov/IronyModManager#314]
**Describe the bug**
I installed Irony mod manager to H drive(where I install stellaris) some times ago, and didn't run it so far.
I heard stellaris have new update, so I run it recently. but when I try to run it, it's shut down by it self and show me fatal error.
I uninstall install version then tried zip version instead, but same thing happened.

**To Reproduce**
1. Open IronyModManager.exe
2. window shows and tell me loading data. update notice shown at bottom right
3. tell me there is mod can not find
4. show me fatal error window then shut down

**Expected behavior**
Irony Mod Manager started

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Access to the path 'H:\System Volume Information' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'H:\System Volume Information' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at IronyModManager.Services.ModService.GetAllModDescriptors(String path, ModSource modSource) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 741
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 374
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace ---

**Version:**
 - OS: [e.g. Windows] Windows 10 Enterprise
 - Irony Version [e.g. 1.5.48] 1.20.24(I download latest version, but it keep saying there is update)

**Additional context**
Sorry I'm not english native and know nothing about programming.

**Comment by hosunggoon** [comment]
I read #306 and check your config file to fix mine. Thanks to support, it works now. Many thanks!
