### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Somnac** [bcssov/IronyModManager#319]
irony throws a fatal error upon attempting to import a mod collection

collection is the latest 'merger of mods' on stellaris. 331 mods, I know I know, I have serious issues with long mod lists.. I thinki my rimworld one has 667 and counting. Wonder how that one works.

I've used this collection before, on another computer - arguably more potent. Used to just: make a new collection, import the mod order fro the zip, merge it all as the creator requests and wait half an hour or more. eventually, all would be ready to boot up. could even test my hand at conflict solving, or add other minor mods into the collection (I know, I know mod addiction)
 
Fatal Error log as follows
Unhandled error ocurred. Please use this information to file a bug report:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value cannot be null. (Parameter 'path3'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path3')
   at System.IO.Path.Combine(String path1, String path2, String path3)
   at IronyModManager.Services.ModBaseService.GetPatchModDirectory(IGame game, String patchOrMergeName) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 668
   at IronyModManager.Services.ModCollectionService.ImportAsync(String file) in D:\Working\IronyModManager\src\IronyModManager.Services\ModCollectionService.cs:line 382
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.<>c__DisplayClass288_0.<<ImportCollectionAsync>b__3>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1106
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.<>c__DisplayClass288_0.<<ImportCollectionAsync>g__importDefault|0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1106
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.ImportCollectionAsync(String path, ImportProviderType type) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1172
   --- End of inner exception stack trace ---

I'm on Windows, Irony's at 1.20.27

Sorry for the troubles, wankers.

**Comment by bcssov** [comment]
Ensure that you actually have irony pointed towards data or custom mod directory in the options screen.

**Comment by Somnac** [comment]
sorry, what do you mean by that? I've directed Irony to the documents/paradox folders when it asks for data directory, and I've provided directions to the steam workshop/281990 folder as a custom mod directory

**Comment by bcssov** [comment]
Then ensure that the collection you're importing is a proper zip, and don't specify workshop folder as a custom mod directory. This is something that Irony should detect on its own.

**Comment by bcssov** [comment]
Problem reproduced, this happens when people use invalid zips to attempt and import into irony. Like manually zipped stuff. Fixed by having Irony reject these kind of zips.
