### ISSUE TITLE
 Crashing on Startup

### ISSUE THREAD

**Issue by SkGrenadier** [bcssov/IronyModManager#323]
**Describe the bug**
Good morning, I found the following error, every time I try to start the mod manager the message of please wait while loading mod data takes a few minutes and from there the mod manager closes

**To Reproduce**
I open the Mod Manager
In the game option I choose Hearts Of Iron 4

**Expected behavior**
Irony Mod Manager started
Show the list of installed Mods

**Logs**

Fatal Error

2021-12-14 01:12:02.2277 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
2021-12-14 02:07:34.4938 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
2021-12-14 02:18:00.0119 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
2021-12-14 02:24:16.3867 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
2021-12-14 02:25:58.2462 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
2021-12-14 02:30:01.0400 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
2021-12-14 02:30:18.9648 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 365
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
2021-12-14 02:32:45.2170 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
2021-12-14 02:37:37.3636 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
   --- End of inner exception stack trace --- System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at IronyModManager.Parser.BaseGenericObjectParser.Convert[T](String value) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 72
   at IronyModManager.Parser.BaseGenericObjectParser.GetValues[T](IEnumerable`1 elements, String[] keys) in D:\Working\IronyModManager\src\IronyModManager.Parser\BaseGenericObjectParser.cs:line 179
   at IronyModManager.Parser.Mod.ModParser.Parse(IEnumerable`1 lines) in D:\Working\IronyModManager\src\IronyModManager.Parser\Mod\ModParser.cs:line 66
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 570
   at IronyModManager.Services.ModService.GetInstalledModsAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 346
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass219_0.<<BindAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.BindAsync(IGame game, Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 621

Version:

OS: Windows 10 Home Single 
Irony Version: v1.20.33

Additional context

Before if I opened but after I opened the Paradox Launcher v2 I started getting this error

I'll wait for your answer, thank you

**Comment by SkGrenadier** [comment]
Good evening, thanks for the reply and sorry for the delay; just the last update has fixed my problem, thanks and keep up the great work.

**Comment by SkGrenadier** [comment]
Good evening, thanks for the reply and sorry for the delay; just the last update has fixed my problem, thanks and keep up the great work.
