### ISSUE TITLE
Exception on startup with empty / invalid mod(s)

### ISSUE THREAD

**Issue by Khest** [bcssov/IronyModManager#324]
**Describe the bug**
Null reference exception on application start. Stacktrace posted below.
I have a mix of local mods in My Documents folder and Steam mods. I also briefly see a popup saying Invalid Mods Detected (see screenshot) for some local mods and my merged mod. Inspecting the .mod files reveal them to be empty (0kb) which is strange as they worked yesterday. I don't know why they are suddenly empty.

**To Reproduce**

**Expected behavior**

**Screenshots**
![bilde](https://user-images.githubusercontent.com/14147760/146590759-a82cd9b9-3b4d-4f39-979e-cd5035cedc97.png)

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.Services.ModService.AreModsSame(IMod mod, IMod otherMod) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 605
   at IronyModManager.Services.ModService.<>c__DisplayClass16_1.<InstallModsAsync>b__7(IMod m) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 401
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at IronyModManager.Services.ModService.<>c__DisplayClass16_0.<InstallModsAsync>b__2(IModInstallationResult p) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 401
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 0
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace ---

**Version:**
 - OS: Windows 10 21H1
 - Irony Version 1.20.37

**Additional context**
By fixing (as in, setting path and name information) the corrupt / empty .mod files the problem disappeared.

**Comment by bcssov** [comment]
That is the problem, something rewrote these mod descriptors and created empty files which doesn't happen in a real world scenario. So not much I can do in this scenario. Do you have any clue what created these?

**Comment by Khest** [comment]
I have no idea what did this, might have been the Paradox launcher as I switch between that and Irony. But honestly no clue, it hasn't happened before. But seeing as it's not something that should happen in real world scenarios I doubt it'll ever happen again. Anyway thanks for getting back to me and keep up the good work!

**Comment by LasmGratel** [comment]
I met the same problem
