### ISSUE TITLE
Crash or Hangup

### ISSUE THREAD

**Issue by Skross111** [bcssov/IronyModManager#33]
Crashing when applying collection or when pressing conflict solver it just gets stuck in random %

error log 

19:27:09.8554 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.IO.Mods.ModWriter.MapPdxPath(ModRegistry registry, IMod mod)
   at IronyModManager.IO.Mods.ModWriter.SyncData(DLCLoad dLCLoad, GameData gameData, ModRegistryCollection modRegistry, IMod mod, Boolean isEnabled)
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters)
   at IronyModManager.Services.ModService.ExportModsAsync(IReadOnlyCollection`1 enabledMods, IReadOnlyCollection`1 regularMods, String collectionName)
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.ApplyCollectionAsync() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 191
   --- End of inner exception stack trace --- System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.IO.Mods.ModWriter.MapPdxPath(ModRegistry registry, IMod mod)
   at IronyModManager.IO.Mods.ModWriter.SyncData(DLCLoad dLCLoad, GameData gameData, ModRegistryCollection modRegistry, IMod mod, Boolean isEnabled)
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters)
   at IronyModManager.Services.ModService.ExportModsAsync(IReadOnlyCollection`1 enabledMods, IReadOnlyCollection`1 regularMods, String collectionName)
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.ApplyCollectionAsync() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 191

**Comment by bcssov** [comment]
It's crashing at a line where it shouldn't crash. I won't be able to reproduce this easily so I'll need you to do the following:
1. Isolate which combination of mods crashes Irony
2. Give me that mod file located in your documents\paradox interactive\stellaris\mod directory
3. Also provide me with your dlc_load.json, game_data.json and mods_registry.json

**Comment by Skross111** [comment]
also using GOG stellaris version

[mods_registry.txt](https://github.com/bcssov/IronyModManager/files/4518801/mods_registry.txt)
[game_data.txt](https://github.com/bcssov/IronyModManager/files/4518809/game_data.txt)
[dlc_load.txt](https://github.com/bcssov/IronyModManager/files/4518815/dlc_load.txt)

really have no idea how should i provide you with thoes files does that work?

ok and it seems it happens with a bunch of mods not all of them for example https://steamcommunity.com/sharedfiles/filedetails/?id=703156866

**Comment by bcssov** [comment]
I've tested this on a combination of many other mods, descriptors etc. I am not asking for the whole mod rather for a single .mod file from the mentioned directory.

Though this is a non Irony issue, rather an issue with the way you installed mods. Your .mod files probably aren't installed correctly.

**Comment by bcssov** [comment]
Not an issue, closing. One final note you did know Irony can install these for you automatically? 

https://github.com/bcssov/IronyModManager/wiki/Installing-New-Mods
