### ISSUE TITLE
Fatal Error on Start

### ISSUE THREAD

**Issue by rtbittaker** [bcssov/IronyModManager#330]
Irony Mod Manager now crashes on startup. I installed 2 Windows updates when shutting down my computer yesterday. 

1)
https://support.microsoft.com/en-us/topic/january-11-2022-kb5009543-os-builds-19042-1466-19043-1466-and-19044-1466-b763552f-73bd-435a-b220-fc3e0bc9765b

2) 
https://support.microsoft.com/en-us/topic/january-11-2022-kb5008876-cumulative-update-for-net-framework-3-5-and-4-8-for-windows-10-version-20h2-windows-server-version-20h2-windows-10-version-21h1-and-windows-10-version-21h2-bb0dbbd8-b24f-4e92-95d2-465e6be223fc

The following is the fatal error thrown by Irony when launching. 
```
Unhandled error ocurred. Please use this information to file a bug report:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.Services.ModService.AreModsSame(IMod mod, IMod otherMod) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 601
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at IronyModManager.Services.ModService.<>c__DisplayClass16_0.<InstallModsAsync>b__2(IModInstallationResult p) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 401
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 0
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 615
   --- End of inner exception stack trace ---
```

**Comment by bcssov** [comment]
One of the descriptor mod files is empty (zero byte file most likely) in the mod folder. Find it and delete it.

**Comment by rtbittaker** [comment]
I think I found it and the crashing has stopped. Thanks for the fast response!
