### ISSUE TITLE
Fatal Error creating Merged Patch

### ISSUE THREAD

**Issue by SwarmoGyats0** [bcssov/IronyModManager#341]
**Describe the bug**
Irony Mod Manager is crashing when I attempt to execute the Merge > Compress function for my mod list (Functional in-game (Stellaris), mostly trying to trim load time and improve performance)

**To Reproduce**
1. Start Irony Mod Manager
2. Select Merge > Compress
3. Let it Run
4. Crashes at 99.9% completion.

**Expected behavior**
A finished merge patch to be created.

**Screenshots**

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:

2022-03-11 09:25:02.6248 Version: 1.21.124+066eccaa0c
OS Description: Microsoft Windows 10.0.19043
Runtime Identifier: win10-x64
 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.IO.IOException: Cannot create a file when that file already exists.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Ionic.Zip.ZipFile.Save()
   at IronyModManager.IO.Mods.ModMergeCompressExporter.Finalize(Int64 id, String exportPath) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModMergeCompressExporter.cs:line 125
   at IronyModManager.Services.ModMergeService.<>c__DisplayClass10_0.<<MergeCompressCollectionAsync>b__6>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.Services\ModMergeService.cs:line 438
--- End of stack trace from previous location ---
   at IronyModManager.Services.ModMergeService.MergeCompressCollectionAsync(String collectionName, String copiedNamePrefix) in D:\Working\IronyModManager\src\IronyModManager.Services\ModMergeService.cs:line 458
   at IronyModManager.ViewModels.Controls.ModifyCollectionControlViewModel.<>c__DisplayClass88_3.<<OnActivated>b__16>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModifyCollectionControlViewModel.cs:line 534
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModifyCollectionControlViewModel.<>c__DisplayClass88_0.<<OnActivated>b__6>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModifyCollectionControlViewModel.cs:line 532
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 89
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 559
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 278
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 96

**Version:**
 In Log

**Additional context**
Running IMM as administrator, I've got all available processing power devoted to it, and I've already solved what the program marks out to be incontrovertible conflicts in the conflict resolver.

**Comment by bcssov** [comment]
Seems like you have AV blocking Irony or multiple instances even of Irony running. The merge compress process should have cleared out the folder that is supposed to create files in but it seems to have failed which is what the error states.

**Comment by SwarmoGyats0** [comment]
Well, I've tried making an exception in my firewall and with the AV in use, as well as disabling both of them before trying the merge and I still get the exact same error. It works and runs fine for a basic merge, but consistently crashes for a compression merge. Definitely not running any other instances of IMM; any notions as to what a solve could be?

**Comment by bcssov** [comment]
Aside from reiterating that something is preventing Irony from clearing the folder where it should compress stuff I cannot offer any additional guidance. Try manually deleting the folder where Irony is going to merge, folder where Irony dumps this zipped stuff is by internal logic cleared beforehand unless something interferes on your computer. The rest is up to you.
