### ISSUE TITLE
Import Fatal Error -- Unhandled Error Occurred 

### ISSUE THREAD

**Issue by tckarpoff** [bcssov/IronyModManager#345]
**Describe the bug**
Fatal error when trying to import a mod list for Stellaris. This list has worked in the last week.

**To Reproduce**
1. Open Irony to Stellaris
2. Import Zip file of mod collection
3. Gets to 6.130% then resets to 0%
4. Reaches 6.130% again and stalls for a few minutes
5. Fatal Error

**Expected behavior**
Import of mod list zip file like usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/26846658/159136339-244f51a2-2e88-4f02-ad1a-c84041ab5ec6.png)
![image](https://user-images.githubusercontent.com/26846658/159136361-142217d6-da43-47b3-8711-99ea64fffa94.png)

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:
[error.log](https://github.com/bcssov/IronyModManager/files/8310012/error.log)

2022-03-19 12:36:17.1476 Version: 1.21.127+d96f4e689b
OS Description: Microsoft Windows 10.0.22000
Runtime Identifier: win10-x64
 System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\LKarp\OneDrive\Documents\Paradox Interactive\Stellaris\mod\MaybeFinal\445f_26f27e3a\events\????-????.txt'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at SharpCompress.Readers.IReaderExtensions.<>c__DisplayClass4_0.<WriteEntryToFile>b__0(String x, FileMode fm)
   at SharpCompress.Common.ExtractionMethods.WriteEntryToFile(IEntry entry, String destinationFileName, ExtractionOptions options, Action`2 openAndWrite)
   at IronyModManager.IO.Mods.ModCollectionExporter.<ImportInternal>g__parseUsingReaderFactory|21_1(<>c__DisplayClass21_0& ) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 457
   at IronyModManager.IO.Mods.ModCollectionExporter.ImportInternal(ModCollectionExporterParams parameters, Boolean importInstance, ICollectionImportResult& collectionImportResult) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 536
   at IronyModManager.IO.Mods.ModCollectionExporter.ImportModDirectoryAsync(ModCollectionExporterParams parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 305
   at IronyModManager.Services.ModCollectionService.ImportAsync(String file) in D:\Working\IronyModManager\src\IronyModManager.Services\ModCollectionService.cs:line 388
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.<>c__DisplayClass288_0.<<ImportCollectionAsync>b__3>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1106
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.<>c__DisplayClass288_0.<<ImportCollectionAsync>g__importDefault|0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1106
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.ImportCollectionAsync(String path, ImportProviderType type) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1172

**Version:**
 - OS: [Windows 10.0.22000]
 - Irony Version [v1.21.127]

**Additional context**
Can attach mod list zip if required.

**Comment by bcssov** [comment]
There was a bug in export of older versions in Irony where they didn't handle properly chinese or japanese characters in filenames. This has been fixed now during export but problem remains in these older exports. I recommend fixing the offending filenames in the zip manually and do a re-import.

**Comment by tckarpoff** [comment]
The file was just re-exported after updating Irony.

**Comment by tckarpoff** [comment]
That fixes it thank you.
