### ISSUE TITLE
error when applying patch

### ISSUE THREAD

**Issue by rubyr47** [bcssov/IronyModManager#367]
**Describe the bug**

**Expected behavior**
Applying mod then the errors came up

**Screenshots**

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:

2022-06-02 23:35:01.4770 Version: 1.21.144+153b940839
OS Description: Microsoft Windows 10.0.22000
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'enabled_mods', line 3, position 0.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 188
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 161
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in D:\Working\IronyModManager\src\IronyModManager.Services\DLCService.cs:line 181
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnActivated>b__68_0() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 192

**Version:**
 - OS: [Windows 10]
 - Irony Version [Latest]

**Additional context**
Mod for CKIII

**Comment by bcssov** [comment]
See:
https://github.com/bcssov/IronyModManager/issues/200#issuecomment-783788786

**Comment by rubyr47** [comment]
okay, thank you !

i do make my own dlc_load.json thing and delete it
