### ISSUE TITLE
Export + Import freezes or crashes due to improper handling of unicode folder name

### ISSUE THREAD

**Issue by gab** [bcssov/IronyModManager#371]
**Describe the bug**
A round trip export-import of a mod with a unicode folder name such as !未使用 causes the import to fail with a freeze or crash.

Personally it happened to me while exporting and then importing the collection [Dogepack Giga](https://steamcommunity.com/sharedfiles/filedetails/?id=2816334383), but I'm providing slimmed-down repro steps so you don't have to export/import 15 GB to repro.

**To Reproduce**
1. Make a collection with just this mod https://steamcommunity.com/sharedfiles/filedetails/?id=1199002146
2. Export the collection
3. Attempt to import the resulting zip
4. Notice that Irony freezes or crashes when trying to handle the folder named !未使用 which ended up as !??? in the zip.

**Screenshots**
Faulty folder name at the top, as seen when opened in 7z manager:
![image](https://user-images.githubusercontent.com/270761/173373191-445f8458-f13c-4c34-8072-bddf67037d21.png)

**Expected behavior**
The round-trip export and import should be successful, and the folder name shouldn't become garbled in the zip file.

**Logs**

```
2022-06-13 01:05:58.2098 Version: 1.21.151+e6788c6d94
OS Description: Microsoft Windows 6.1.7601 Service Pack 1
Runtime Identifier: win7-x64
 System.IO.IOException: La syntaxe du nom de fichier, de rÃ©pertoire ou de volume est incorrecte. : 'D:\Mods\IronyModManager_mod_folder\DogePack_Giga_v6\1771_cbe93f48\!???'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at IronyModManager.IO.Mods.ModCollectionExporter.<ImportInternal>g__parseUsingArchiveFactory|21_2(<>c__DisplayClass21_0& ) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 511
   at IronyModManager.IO.Mods.ModCollectionExporter.ImportInternal(ModCollectionExporterParams parameters, Boolean importInstance, ICollectionImportResult& collectionImportResult) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 530
2022-06-13 01:39:35.1391 Version: 1.21.151+e6788c6d94
OS Description: Microsoft Windows 6.1.7601 Service Pack 1
Runtime Identifier: win7-x64
 System.IO.IOException: La syntaxe du nom de fichier, de rÃ©pertoire ou de volume est incorrecte. : 'D:\Mods\IronyModManager_mod_folder\DogePack_Giga_v6\1771_cbe93f48\!???'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at IronyModManager.IO.Mods.ModCollectionExporter.<ImportInternal>g__parseUsingArchiveFactory|21_2(<>c__DisplayClass21_0& ) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 511
   at IronyModManager.IO.Mods.ModCollectionExporter.ImportInternal(ModCollectionExporterParams parameters, Boolean importInstance, ICollectionImportResult& collectionImportResult) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 530
2022-06-13 08:55:44.1579 Version: 1.21.151+e6788c6d94
OS Description: Microsoft Windows 6.1.7601 Service Pack 1
Runtime Identifier: win7-x64
 System.IO.IOException: La syntaxe du nom de fichier, de rÃ©pertoire ou de volume est incorrecte. : 'D:\Mods\IronyModManager_mod_folder\DogePack_Giga_v6\1771_cbe93f48\!???'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at IronyModManager.IO.Mods.ModCollectionExporter.<ImportInternal>g__parseUsingArchiveFactory|21_2(<>c__DisplayClass21_0& ) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 511
   at IronyModManager.IO.Mods.ModCollectionExporter.ImportInternal(ModCollectionExporterParams parameters, Boolean importInstance, ICollectionImportResult& collectionImportResult) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 530
```

```
2022-06-13 02:52:24.2050 Version: 1.21.151+e6788c6d94
OS Description: Microsoft Windows 6.1.7601 Service Pack 1
Runtime Identifier: win7-x64
 System.IO.IOException: La syntaxe du nom de fichier, de rÃ©pertoire ou de volume est incorrecte. : 'D:\Mods\IronyModManager_mod_folder\DogePack_Giga_v6\1771_cbe93f48\!???'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at IronyModManager.IO.Mods.ModCollectionExporter.<ImportInternal>g__parseUsingReaderFactory|21_1(<>c__DisplayClass21_0& ) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 457
   at IronyModManager.IO.Mods.ModCollectionExporter.ImportInternal(ModCollectionExporterParams parameters, Boolean importInstance, ICollectionImportResult& collectionImportResult) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 536
   at IronyModManager.IO.Mods.ModCollectionExporter.ImportModDirectoryAsync(ModCollectionExporterParams parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModCollectionExporter.cs:line 305
   at IronyModManager.Services.ModCollectionService.ImportAsync(String file) in D:\Working\IronyModManager\src\IronyModManager.Services\ModCollectionService.cs:line 388
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.<>c__DisplayClass288_0.<<ImportCollectionAsync>b__3>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1106
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.<>c__DisplayClass288_0.<<ImportCollectionAsync>g__importDefault|0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1106
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.ImportCollectionAsync(String path, ImportProviderType type) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1172
```

**Version:**
 - OS: win7-x64 (Microsoft Windows 6.1.7601 Service Pack 1)
 - Irony Version 1.21.151

**Additional context**
There are multiple mods included in popular mod collections that use the same folder name Irony doesn't like:
![image](https://user-images.githubusercontent.com/270761/173372093-91f44d42-ea11-48e5-b5b7-cdc35323ca20.png)

**Comment by bcssov** [comment]
Note: This is only when you export whole collections and not regular Irony exports. It's fixed pending release in a future update.
