### ISSUE TITLE
Unhandled error in conflict solver initial loading

### ISSUE THREAD

**Issue by semiliterate** [bcssov/IronyModManager#374]
Alt-tabbed away during the first phase of pulling Definitions from mods. Several minutes passed, so can't be sure it hadn't advanced to another stage. Full traceback follows. Am not aware of what any of this means, if you need more information or details I should be able to respond to requests.

ETA: was running it in Analyze Only and the program force closed after the error, in case those aren't detailed below

Error message:

Unhandled error ocurred. Please use this information to file a bug report:

2022-06-20 13:23:05.7964 Version: 1.21.151+e6788c6d94
OS Description: Microsoft Windows 10.0.19044
Runtime Identifier: win10-x64
 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.IO.IOException: Data error (cyclic redundancy check). : 'D:\Program Files\SteamLibrary\steamapps\common\Stellaris\gfx\models\ships\other\eventship_08.mesh'
   at System.IO.Strategies.OSFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.FileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Data.HashFunction.Core.Utilities.UnifiedData.StreamData.ForEachGroup(Int32 groupSize, Action`3 action, Action`3 remainderAction, CancellationToken cancellationToken)
   at System.Data.HashFunction.MetroHash.MetroHash128_Implementation.ComputeHashInternal(IUnifiedData data, CancellationToken cancellationToken)
   at System.Data.HashFunction.Core.HashFunctionBase.ComputeHash(Stream data, CancellationToken cancellationToken)
   at IronyModManager.Shared.Extensions.CalculateSHA(Stream stream) in D:\Working\IronyModManager\src\IronyModManager.Shared\Extensions.Stream.cs:line 60
   at IronyModManager.IO.DiskFileReader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in D:\Working\IronyModManager\src\IronyModManager.IO\Readers\DiskFileReader.cs:line 196
   at IronyModManager.IO.Readers.Reader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in D:\Working\IronyModManager\src\IronyModManager.IO\Readers\Reader.cs:line 174
   at IronyModManager.Services.GameIndexService.<>c__DisplayClass5_5.<<IndexDefinitionsAsync>b__9>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.Services\GameIndexService.cs:line 148
--- End of stack trace from previous location ---
   at IronyModManager.Services.GameIndexService.<>c__DisplayClass5_4.<<IndexDefinitionsAsync>b__8>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.Services\GameIndexService.cs:line 158
--- End of stack trace from previous location ---
   at IronyModManager.Services.GameIndexService.IndexDefinitionsAsync(IGame game, IEnumerable`1 versions, IIndexedDefinitions indexedDefinitions) in D:\Working\IronyModManager\src\IronyModManager.Services\GameIndexService.cs:line 159
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass141_0.<<AnalyzeModsAsync>b__0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 497
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(Int64 id, PatchStateMode mode, IEnumerable`1 versions) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 495
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass146_0.<<OnActivated>g__runAnalysis|0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 683
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 89
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 559
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 278
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 96

**Comment by bcssov** [comment]
It's your hard drive CRC error indicates that the disk is corrupt or damaged in some way.
