### ISSUE TITLE
Had to move documents folder, now Irony crashes as soon as I launch it

### ISSUE THREAD

**Issue by JardinthePotato** [bcssov/IronyModManager#384]
**Describe the bug**
I had to move my documents folder from my old failing hard drive to another one, now IMM crashes a few seconds after I launch it.

**To Reproduce**
1. Launch
2. It crashes
3. 
4. 

**Expected behavior**
for it not to crash

**Logs**
2022-08-01 13:03:14.4870 Version: 1.22.143+a2f9e9dd40
OS Description: Microsoft Windows 10.0.19044
Runtime Identifier: win10-x64
 System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\Documents\Paradox Interactive\Hearts of Iron IV\mod'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at IronyModManager.IO.Mods.ModWriter.CreateModDirectoryAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 118
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 419
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 649

**Version:**
 - OS: Windows 10
 - Irony Version - latest stable

**Comment by bcssov** [comment]
Usually when someone moves their documents location the previous location is still available in your case your whole drive letter is unavailable. So:
1. Delete database_1.22.json in %appdata% (see homepage for location)
2. Edit database_1.22.json manually to update paths

Doing 1 means you lose all Irony settings and collections.
