### ISSUE TITLE
Fatal Error on game launch

### ISSUE THREAD

**Issue by Meeperdude** [bcssov/IronyModManager#388]
**Describe the bug**
App claims a fatal error when Stellaris is launched
**To Reproduce**
1. Install irony through the instructutions in the FAQ
2. Import a mod collection from zip file
4. add additional mod from disk
5. use launch game option
6. 

**Expected behavior**
stellaris would launch
**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.
Unhandled error ocurred. Please use this information to file a bug report:

2022-08-10 00:43:57.8070 Version: 1.22.147+1a3546330a
OS Description: Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Runtime Identifier: osx.12-x64
 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.DllNotFoundException: Unable to load shared library 'steam_api' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libsteam_api, 0x0001): tried: 'libsteam_api' (no such file), '/usr/local/lib/libsteam_api' (no such file), '/usr/lib/libsteam_api' (no such file), '/Applications/Stellaris_Mods/IronyModManager.app/Contents/MacOS/libsteam_api' (no such file)
   at Steamworks.NativeMethods.SteamAPI_IsSteamRunning()
   at IronyModManager.IO.Platforms.SteamHandler.InitAsync(Int64 appId) in D:\Working\IronyModManager\src\IronyModManager.IO\Platforms\SteamHandler.cs:line 121
   at IronyModManager.Services.ExternalProcessHandlerService.LaunchSteamAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager.Services\ExternalProcessHandlerService.cs:line 98
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass145_0.<<OnActivated>g__ensureSteamIsRunning|21>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 807
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass145_0.<<OnActivated>g__launchGame|22>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 854
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass145_0.<<OnActivated>b__23>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 884
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 73
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 559
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4336
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 97
**Version:**
 - OS: OSX Monterey
 - Irony Version [e.g. 1.22.147]

**Additional context**

**Comment by bcssov** [comment]
Wish I had the capability to test stuff on OSX. I believed I followed proper instructions for OSX when I took a package. 

For the time being set this flag to true to bypass the new steam `is running logic`:
https://github.com/bcssov/IronyModManager/blob/1a3546330a5b026b96287db1ad4032f7965d9ed5/src/IronyModManager/appSettings.json#L21

If you're willing to be a guinea pig to help fix this hop onto Irony discord (link on the homepage).

**Comment by bcssov** [comment]
This is a problem with publish procedures, seems I followed instructions wrong or the instructions were wrong or I literally followed instructions. Whatever it is you can fix this by copying these files to root directory from steam_api.bundle\contents\macos

https://github.com/bcssov/IronyModManager/tree/master/References/Conditional/Steamworks/OSX-Linux-x64/steam_api.bundle/Contents/MacOS

By root I mean where IronyModManager.dll is located.

This will be fixed in the new scheduled release.
