### ISSUE TITLE
When modifing a modlist crash happens

### ISSUE THREAD

**Issue by potter9090** [bcssov/IronyModManager#390]
**Describe the bug**
As I take a mod out the list it crashes

**To Reproduce**
1. In existing list take out a mod
2. Crashes

**Expected behavior**
Should just take out the mod, be able to apply and lauch the game

**Screenshots**
 (https://imgur.com/a/MkGLRQK)

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:

2022-08-17 17:12:13.6343 Version: 1.23.39+a97e316d79
OS Description: Microsoft Windows 10.0.19043
Runtime Identifier: win10-x64
 System.IndexOutOfRangeException: Could not recycle container: not materialized.
   at Avalonia.Controls.Generators.ItemContainerGenerator`1.TryRecycle(Int32 oldIndex, Int32 newIndex, Object item) in /_/src/Avalonia.Controls/Generators/ItemContainerGenerator`1.cs:line 81
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.RecycleContainersForMove(Int32 delta) in /_/src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs:line 432
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.set_OffsetValue(Double value) in /_/src/Avalonia.Controls/Presenters/ItemVirtualizerSimple.cs:line 50
   at Avalonia.Controls.Presenters.ItemVirtualizer.set_Offset(Vector value) in /_/src/Avalonia.Controls/Presenters/ItemVirtualizer.cs:line 151
   at Avalonia.Controls.Presenters.ItemsPresenter.Avalonia.Controls.Primitives.IScrollable.set_Offset(Vector value) in /_/src/Avalonia.Controls/Presenters/ItemsPresenter.cs:line 92
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Skip`1.Count._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Skip.cs:line 59
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs:line 70
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 761
   at Avalonia.Controls.Presenters.ScrollContentPresenter.set_Offset(Vector value) in /_/src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs:line 129
   at Avalonia.Controls.Presenters.ScrollContentPresenter.OnPointerWheelChanged(PointerWheelEventArgs e) in /_/src/Avalonia.Controls/Presenters/ScrollContentPresenter.cs:line 439
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 123
   at Avalonia.Input.MouseDevice.MouseWheel(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, Vector delta, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 326
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 144
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 518
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in D:\Working\IronyModManager\src\IronyModManager\Program.cs:line 97

**Version:**
2022-08-17 17:12:13.6343 Version: 1.23.39+a97e316d79
OS Description: Microsoft Windows 10.0.19043

**Additional context**

I was already using with sucess this modlist, but now I have updated Irony, as I did i cannot modify, any mod that I take out crashes the program.

**Comment by bcssov** [comment]
This is a known Avalonia issue (framework I'm using) and this sort of thing happens from time to time. Until it's fixed there it will happen from time to time in this program.

Restart the mod manager and the issue should sort itself out. 

Closing as it's out of my hands.
