### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by Hippapodacow** [bcssov/IronyModManager#397]
I start Irony in its hoi4 configuration and it does this:

Unhandled error ocurred. Please use this information to file a bug report:

2022-10-16 13:34:16.4943 Version: 1.23.56+ff92452b03
OS Description: Microsoft Windows 10.0.22000
Runtime Identifier: win10-x64
 System.IO.IOException: The cloud file provider is not running. : 'C:\Users\camer\OneDrive\Documents\Paradox Interactive\Hearts of Iron IV\mod\ugc_1081189937.mod'
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at IronyModManager.IO.Readers.BaseSpecializedDiskReader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in D:\Working\IronyModManager\src\IronyModManager.IO\Readers\BaseSpecializedDiskReader.cs:line 138
   at IronyModManager.IO.Readers.Reader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in D:\Working\IronyModManager\src\IronyModManager.IO\Readers\Reader.cs:line 174
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 610
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 406
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 649

Have tried reinstalling, which did not help.

**Comment by bcssov** [comment]
See: https://github.com/bcssov/IronyModManager/issues/249#issuecomment-831664161

**Comment by Hippapodacow** [comment]
Which would be fine but there's no way to change the directory Irony is looking for from the cloud one to the local one.

**Comment by Hippapodacow** [comment]
Ok, fixed it. For anyone in the future with this problem, you're gonna want to open the OneDrive (or similar) app, make sure it's on and if it is, reinstall Irony.
