### ISSUE TITLE
crashed after set "refresh descriptor before playing" for Vic3

### ISSUE THREAD

**Issue by Sa-ku-mo** [bcssov/IronyModManager#403]
**Describe the bug**
Irony continuously crash in my PC now, even after a fully uninstall and install.
**To Reproduce**
1. I created a mod without .metadata for Vic3, of course it can't be read
2. Then I try "refresh descriptor before playing" option
3. It crashed, maybe 1 minute after open it every time
4. uninstalled, and installed again. the "a.mod" in error log below has been deleted before re-install, but like a ghost
**Expected behavior**
just stop the fatal error...

**Logs**
2022-10-30 10:23:34.2513 Version: 1.24.59-alpha+183b5632ab
OS Description: Microsoft Windows 10.0.22000
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonSerializationException: Error converting value "mod/a.mod" to type 'IronyModManager.IO.Mods.Models.Paradox.Common.EnabledMod'. Path 'enabledMods[0]', line 1, position 27.
 ---> System.ArgumentException: Could not cast or convert from System.String to IronyModManager.IO.Mods.Models.Paradox.Common.EnabledMod.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 128
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in D:\Working\IronyModManager\src\IronyModManager.Services\DLCService.cs:line 183
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnActivated>b__69_0() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 200
**Version:**
 - OS: Win11
 - Irony Version 1.24.59-alpha

**Additional context**
Or if there is a way totally clear the cache containing game directions and other things?

**Comment by bcssov** [comment]
First if you're going to mod the game, learn it's basics. They changed how mods are structured.
1. Create a proper mod which contains metadata.json. Old .mod formats don't work anymore.
2. The content_load.json contains old dlc_load.json format; which is invalid so of course Irony is going to crash. Delete content_load.json and let irony write proper data.
