### ISSUE TITLE
Crashing in Conflict Solver

### ISSUE THREAD

**Issue by Morcleon** [bcssov/IronyModManager#408]
**Describe the bug**
Program occasionally crashes while in Conflict Solver. Seems to be time based (crashes after some amount of time vs crashing upon doing a specific action), as I've left it open for a few minutes and it will just crash on its own. It's done it for a number of modsets, both one that's achievement compatible, and one that's not.

**To Reproduce**
1. Open IMM
2. Activate Conflict Solver (default)
3. Wait

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:

2022-11-11 13:39:50.0835 Version: 1.24.81+ebb6106bc5
OS Description: Microsoft Windows 10.0.19044
Runtime Identifier: win10-x64
 RepoDb.Exceptions.MissingFieldsException: There are no database fields found for table 'playsets'. Make sure that the target table 'playsets' is present in the database and/or at least a single field is available.
   at RepoDb.DbFieldCache.ValidateDbFields(String tableName, IEnumerable`1 dbFields)
   at RepoDb.DbFieldCache.GetAsyncInternal[TDbConnection](TDbConnection connection, String tableName, IDbTransaction transaction, Boolean enableValidation, CancellationToken cancellationToken)
   at RepoDb.CommandTextCache.GetTargetFieldsAsync(IDbConnection connection, String tableName, IEnumerable`1 fields, IDbTransaction transaction, CancellationToken cancellationToken)
   at RepoDb.CommandTextCache.GetQueryTextAsync(QueryRequest request, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.QueryAsyncInternalBase[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.QueryAsyncInternal[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.RecreateCollectionV2Async(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 228
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.ExportAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 120
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass7_0.<<ApplyModsAsync>b__2>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 114
--- End of stack trace from previous location ---
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 117

**Version:**
 - OS: Windows 10
 - Irony Version 1.24.81

**Comment by bcssov** [comment]
See: https://github.com/bcssov/IronyModManager/issues/128#issuecomment-706145417

Be sure to delete the beta db as well if you're using beta pdx launcher.
