### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Namerian** [bcssov/IronyModManager#409]
**Describe the bug**
Crashed when I pressed "resolve"

**Logs**
Unhandled error ocurred. Please use this information to file a bug report:

2022-11-11 20:49:53.7308 Version: 1.24.81+ebb6106bc5
OS Description: Linux 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022
Runtime Identifier: ubuntu.22.04-x64
 RepoDb.Exceptions.MissingFieldsException: There are no database fields found for table 'playsets'. Make sure that the target table 'playsets' is present in the database and/or at least a single field is available.
   at RepoDb.DbFieldCache.ValidateDbFields(String tableName, IEnumerable`1 dbFields)
   at RepoDb.DbFieldCache.GetAsyncInternal[TDbConnection](TDbConnection connection, String tableName, IDbTransaction transaction, Boolean enableValidation, CancellationToken cancellationToken)
   at RepoDb.CommandTextCache.GetTargetFieldsAsync(IDbConnection connection, String tableName, IEnumerable`1 fields, IDbTransaction transaction, CancellationToken cancellationToken)
   at RepoDb.CommandTextCache.GetQueryTextAsync(QueryRequest request, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.QueryAsyncInternalBase[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.QueryAsyncInternal[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.RecreateCollectionV2Async(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 228
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.ExportAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 120
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass7_0.<<ApplyModsAsync>b__2>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 114
--- End of stack trace from previous location ---
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 117

**Version:**
 - OS: Ubuntu
 - Irony Version: 1.24.81

**Comment by bcssov** [comment]
Same, see: https://github.com/bcssov/IronyModManager/issues/408#issuecomment-1312085300

**Comment by Spritzen** [comment]
I had this, all I had to do was to open the normal game launcher (something which I never use). It was out of date and just needed updating.

**Comment by Namerian** [comment]
I use the default launcher all the time so it i up to date. It seems to be a database issue inside the irony mod manager, it cannot find a field it is looking for.

**Comment by bcssov** [comment]
The error states that playsets table is missing as in does not exist.

**Comment by Namerian** [comment]
Do I have to create it?

**Comment by bcssov** [comment]
If you delete the database file Irony will create a new database, or to be more precise copy one that it has shipped.

**Comment by Namerian** [comment]
Deleting the two databases in the stellaris folder seems to have fixed the issue.
