### ISSUE TITLE
Crash when resolving issue

### ISSUE THREAD

**Issue by Dukko** [bcssov/IronyModManager#42]
Hello! I am getting a crash when trying to resolve an issue. Here's the log.

`2020-04-27 09:36:45.5125 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Additional text encountered after finished reading JSON content: b. Path '', line 1, position 5926.)
 ---> Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: b. Path '', line 1, position 5926.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.ModWriter.LoadPdxModelAsync[T](String path)
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters)
   at IronyModManager.Services.ModService.ExportModPatchDefinitionAsync(IConflictResult conflictResult, IDefinition definition, String collectionName, Boolean resolve)
   at IronyModManager.ViewModels.MainConflictSolverControlViewModel.ResolveConflictAsync(Boolean resolve) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\MainConflictSolverViewModel.cs:line 575
   --- End of inner exception stack trace --- Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: b. Path '', line 1, position 5926.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.ModWriter.LoadPdxModelAsync[T](String path)
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters)
   at IronyModManager.Services.ModService.ExportModPatchDefinitionAsync(IConflictResult conflictResult, IDefinition definition, String collectionName, Boolean resolve)
   at IronyModManager.ViewModels.MainConflictSolverControlViewModel.ResolveConflictAsync(Boolean resolve) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\MainConflictSolverViewModel.cs:line 575
`

**Comment by bcssov** [comment]
That's an external component JSON serializer throwing an error. One of your jsons is corrupt? I'd need to take a look at your dlc_load.json, game_data.json and mods_registry.json to see what exactly is happening.

**Comment by bcssov** [comment]
Closing due to inactivity.
