### ISSUE TITLE
Crash on selecting game

### ISSUE THREAD

**Issue by Pryncezna** [bcssov/IronyModManager#423]
**Describe the bug**
Irony consistently crashes for me a couple of seconds after I choose Stellaris in the drop-down menu. It displays my mods for a moment, then it crashes. Terribly sorry if it's something trivial, I'm not quite experienced.

**To Reproduce**
1.  Launch Irony
2.  Choose Stellaris as the game to be managed

**Logs**
2023-01-30 22:34:32.5939 Version: 1.24.107+37845c91b2
OS Description: Microsoft Windows 10.0.19044
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: #. Path '', line 3, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 113
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in D:\Working\IronyModManager\src\IronyModManager.Services\DLCService.cs:line 183
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnSelectedGameChanged>b__70_0() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 270
2023-01-30 22:39:54.7649 Version: 1.24.107+37845c91b2
OS Description: Microsoft Windows 10.0.19044
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: #. Path '', line 3, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 113
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in D:\Working\IronyModManager\src\IronyModManager.Services\DLCService.cs:line 183
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnActivated>b__69_0() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 200

**Comment by bcssov** [comment]
Delete dlc_load.json it's corrupt.

**Comment by Pryncezna** [comment]
Worked! Thanks a lot!!
