### ISSUE TITLE
[Bug] Unhandled fatal error; see attached stack trace

### ISSUE THREAD

**Issue by GreenKeldeo** [bcssov/IronyModManager#428]
**Describe the bug**
Unhandled error - refer to stack trace.

**To Reproduce**
1. Launch Irony
2. Start scrolling modlist

**Expected behavior**
Irony Mod Manager does not crash.

**Screenshots**
Refer to stack trace.

**Version:**
 - OS: Windows 11 Home 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
 - Irony Version 1.24.114

**Additional context**
N/A; let me know if you need more information

**Logs**
[2023-03-11_Error.log](https://github.com/bcssov/IronyModManager/files/10949683/2023-03-11_Error.log)
[2023-03-11_Fatal.log](https://github.com/bcssov/IronyModManager/files/10949684/2023-03-11_Fatal.log)

Trace:
```Unhandled error ocurred. Please use this information to file a bug report:

2023-03-11 16:51:12.8825 Version: 1.24.114+164e09e574
OS Description: Microsoft Windows 10.0.22621
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'OverwrittenConflicts[1357].OverwrittenFileNames[0]', line 1, position 7103200.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at IronyModManager.DI.Json.JsonDIConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\Working\IronyModManager\src\IronyModManager.DI\Json\JsonDIConverter.cs:line 56
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at IronyModManager.DI.Json.JsonDIConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\Working\IronyModManager\src\IronyModManager.DI\Json\JsonDIConverter.cs:line 56
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at IronyModManager.DI.JsonDISerializer.Deserialize[T](String text) in D:\Working\IronyModManager\src\IronyModManager.DI\JsonDISerializer.cs:line 50
   at IronyModManager.IO.Mods.ModPatchExporter.GetPatchStateInternalAsync(ModPatchExporterParameters parameters, Boolean loadExternalCode) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModPatchExporter.cs:line 767
   at IronyModManager.IO.Mods.ModPatchExporter.GetPatchStateAsync(ModPatchExporterParameters parameters, Boolean loadExternalCode) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModPatchExporter.cs:line 285
   at IronyModManager.Services.ModPatchCollectionService.<>c__DisplayClass35_0.<<PatchModNeedsUpdateAsync>g__evalState|1>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 1338
--- End of stack trace from previous location ---
   at IronyModManager.Services.ModPatchCollectionService.PatchModNeedsUpdateAsync(String collectionName, IReadOnlyCollection`1 loadOrder) in D:\Working\IronyModManager\src\IronyModManager.Services\ModPatchCollectionService.cs:line 1437
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.<>c__DisplayClass315_0.<<HandleCollectionPatchStateAsync>b__0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1126
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.CollectionModsControlViewModel.HandleCollectionPatchStateAsync(String collection) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\CollectionModsControlViewModel.cs:line 1126```

**Comment by bcssov** [comment]
In game mod directory (docs\pdx interactive\{game}\mod) locate IronyModManager_{collection folder name} state.irony file and see if state.tmp or state.bak exist.

Namely this critical mod patch collection file is corrupt. Probably due to sudden crash or shutdown while you were resolving conflicts. 

If all else fails delete the whole ironymodmanager_{collection name} folder or state.irony file. This will completely reset your patch mod though.

**Comment by GreenKeldeo** [comment]
> In game mod directory (docs\pdx interactive\{game}\mod) locate IronyModManager_{collection folder name} state.irony file and see if state.tmp or state.bak exist.
> 
> Namely this critical mod patch collection file is corrupt. Probably due to sudden crash or shutdown while you were resolving conflicts. 
> 
> If all else fails delete the whole ironymodmanager_{collection name} folder or state.irony file. This will completely reset your patch mod though.

Thanks; deleting the patch mod stopped it from crashing in a loop
