### ISSUE TITLE
Fatal Error when clicking Import

### ISSUE THREAD

**Issue by ctsv4vendetta** [bcssov/IronyModManager#440]
**Description**
Click import to import modlist order and Irony throws "Fatal Error". When trying to check file directories in the options, Irony throws "Fatal Error" as well. 

**To Reproduce Import Error**
1. Open Irony
2. Select Stellaris
3. Click "Import"
4. Fatal Error

**To Reproduce Directory Error**
1. Open Irony
2. Select Stellaris
3. Click "Options"
4. Click three dots next to "Data Directory"
5. Fatal Error (same error log as Import error)

**Expected behavior**
Irony opens import dialog box for file selection (I think that's what happens I haven't used Irony in quite a while)
Irony opens data directory dialog box for directory selection

**Screenshots**

**Logs**
Unhandled error occurred. Please use this information to file a bug report:

2023-05-10 15:52:00.0866 Version: 1.24.128+f20ac22823
OS Description: Microsoft Windows 10.0.19044
Runtime Identifier: win10-x64
 System.IO.IOException: An unexpected network error occurred. : 'Q:\'
   at System.IO.DriveInfo.get_VolumeLabel()
   at Avalonia.Win32.WindowsMountedVolumeInfoListener.<>c.<Poll>b__4_1(DriveInfo p) in /_/src/Windows/Avalonia.Win32/WindowsMountedVolumeInfoListener.cs:line 49
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at Avalonia.Win32.WindowsMountedVolumeInfoListener.Poll(Int64 _) in /_/src/Windows/Avalonia.Win32/WindowsMountedVolumeInfoListener.cs:line 35
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.Tick() in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 168
   at System.Reactive.Linq.ObservableImpl.Timer.Periodic._.<>c.<Run>b__4_0(_ this) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Timer.cs:line 141
   at System.Reactive.Concurrency.Scheduler.<>c__67`1.<SchedulePeriodic>b__67_0(ValueTuple`2 t) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.Emulation.cs:line 79
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1.<>c.<Tick>b__5_0(PeriodicallyScheduledWorkItem`1 closureWorkItem) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 127
   at System.Reactive.Concurrency.AsyncLock.<>c__5`1.<Wait>b__5_0(Delegate actionObject, Object stateObject) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 53
   at System.Reactive.Concurrency.AsyncLock.Wait(Object state, Delegate delegate, Action`2 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 125
   at System.Reactive.Concurrency.AsyncLock.Wait[TState](TState state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 53
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1.Tick() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 125
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.Tick() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 210
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.<>c.<.ctor>b__2_0(Object this) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs:line 207
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Version:**
 - OS: Windows 10
 - Irony Version v1.24.128

**Additional context**

**Comment by bcssov** [comment]
Seems like you told irony to look at folder with drive letter Q which doesn't exists. For easy fix delete database_1.24 in %appdata%\mario\ironymodmanager or edit json and remove this q letter. By deleting the file you lose all irony settings and playsets.

**Comment by ctsv4vendetta** [comment]
I deleted the database_1.24 file but the error still pops up when clicking import. I don't know why it keeps trying to go to my quickbooks server. That's where the Q comes from.

**Comment by ctsv4vendetta** [comment]
I disconnected my PC from the Q server, I don't need it anyway. It then tried to connect to another server that I don't need and gave the same error this time with a W. Disconnected that server and finally it's working. How can I direct it to the C drive rather than my servers/drives I use for work?

**Comment by bcssov** [comment]
Yeah that would be framework bug, it seems it's caused to permissions. I might be able to fix it on my end but update won't be available for a while.
