### ISSUE TITLE
Imorting Json Crashes Irony

### ISSUE THREAD

**Issue by CoganTheDestroyer** [bcssov/IronyModManager#455]
**Describe the bug**

**To Reproduce**
1. Use the import feature on a json modlist file

**Expected behavior**
The modlist would be imported

**Screenshots**

**Logs**
2023-07-11 17:29:54.6846 Version: 1.24.157+7e269fd3ba
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win10-x64
 System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'Mods[0]', line 1, position 25558.) (Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'Mods[0]', line 1, position 25558.)
 ---> Newtonsoft.Json.JsonSerializationException: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'Mods[0]', line 1, position 25558.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at IronyModManager.DI.Json.JsonDIConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\Working\IronyModManager\src\IronyModManager.DI\Json\JsonDIConverter.cs:line 56
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at IronyModManager.DI.Json.JsonDIConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\Working\IronyModManager\src\IronyModManager.DI\Json\JsonDIConverter.cs:line 56
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at IronyModManager.DI.JsonDISerializer.Deserialize[T](String text) in D:\Working\IronyModManager\src\IronyModManager.DI\JsonDISerializer.cs:line 50
   at IronyModManager.IO.Mods.Importers.ParadoxLauncherImporter.<>c__DisplayClass5_0.<<JsonImportAsync>g__parseV2|0>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Importers\ParadoxLauncherImporter.cs:line 137
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) Newtonsoft.Json.JsonSerializationException: Unexpected initial token 'String' when populating object. Expected JSON object or array. Path 'Mods[0]', line 1, position 25558.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at IronyModManager.DI.Json.JsonDIConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\Working\IronyModManager\src\IronyModManager.DI\Json\JsonDIConverter.cs:line 56
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at IronyModManager.DI.Json.JsonDIConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in D:\Working\IronyModManager\src\IronyModManager.DI\Json\JsonDIConverter.cs:line 56
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at IronyModManager.DI.JsonDISerializer.Deserialize[T](String text) in D:\Working\IronyModManager\src\IronyModManager.DI\JsonDISerializer.cs:line 50
   at IronyModManager.IO.Mods.Importers.ParadoxLauncherImporter.<>c__DisplayClass5_0.<<JsonImportAsync>g__parseV3|1>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Importers\ParadoxLauncherImporter.cs:line 180<---

**Version:**
 - OS: Windows
 - 1.24.157+7e269fd3ba

**Additional context**
I would attach the json file but github does not support it.

**Comment by bcssov** [comment]
You are using the wrong import type.

**Comment by CoganTheDestroyer** [comment]
> You are using the wrong import type.

But it's the only json file provided and none of the other files show up with any of the import options.

**Comment by bcssov** [comment]
Still doesn't change the fact you're using the wrong import function. Irony's own mod collections (exports) accept only zip files.

**Comment by CoganTheDestroyer** [comment]
> Still doesn't change the fact you're using the wrong import function. Irony's own mod collections (exports) accept only zip files.

Oh I see. The creator of the mod collection I'm using wrote the instructions poorly and made it seem as though I only needed the json file inside the folder provided. Thank you for help.
