### ISSUE TITLE
CTD in conflict solver with unhandled exception error message

### ISSUE THREAD

**Issue by Spacewolf4** [bcssov/IronyModManager#456]
**Describe the bug**
crash to desktop during use of conflict solver - Unhandled exception message produced

**To Reproduce**
1. Activate conflict solver in Advanced mode
2. Resolve one conflict
3. Upon loading next conflict, CTD results

**Expected behavior**
No CTD

**Screenshots**

**Logs**
Unhandled error occurred. Please use this information to file a bug report:

2023-07-23 10:33:45.2796 Version: 1.25.113+42af43f098
OS Description: Microsoft Windows 10.0.22621
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: Invalid property identifier character: “. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.ExportDLCLoadModsAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 206
   at IronyModManager.IO.Mods.Exporter.JsonExporter.ExportModsAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 97
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass7_0.<<ApplyModsAsync>b__3>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 114
--- End of stack trace from previous location ---
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 116

**Version:**
OS: Windows 11 Home 22H2 build 22621.1992
Irony version 1.25.113

**Additional context**
Unsure what to add.

**Comment by bcssov** [comment]
This shows that dlc_load.json is possibly corrupt. Try deleting it and it should work.

**Comment by bcssov** [comment]
It should be documents\pdx\stellaris. And if it's not dlc_load.json it's one of the others. Try deleting one by one and restoring to see which one is it. Or you can use online json validator somewhere to find the json which is corrupt.

**Comment by bcssov** [comment]
Closing this then. Still, this qualifies as corrupt json.
