### ISSUE TITLE
CTD was able to select stellaris now it wont start

### ISSUE THREAD

**Issue by Timbletop** [bcssov/IronyModManager#459]
**Describe the bug**
i only receive a fatal error and it CTD.

**To Reproduce**
1. launched exe
2. IMM starts
3. Fatal error shows
4. IMM automatically CTD

**Expected behavior**
IMM starts

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.
Unhandled error occurred. Please use this information to file a bug report:

2023-07-30 14:10:39.8254 Version: 1.25.115+7da9204a0e
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win10-x64
 System.IO.IOException: The cloud file provider is not running. : 'C:\Users\tzezp\OneDrive\Documents\Paradox Interactive\Stellaris\mod\ugc_1366676488.mod'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at IronyModManager.IO.Readers.BaseSpecializedDiskReader.ReadInternal(String[] files, String path) in D:\Working\IronyModManager\src\IronyModManager.IO\Readers\BaseSpecializedDiskReader.cs:line 153
   at IronyModManager.IO.Readers.BaseSpecializedDiskReader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in D:\Working\IronyModManager\src\IronyModManager.IO\Readers\BaseSpecializedDiskReader.cs:line 132
   at IronyModManager.IO.Readers.Reader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in D:\Working\IronyModManager\src\IronyModManager.IO\Readers\Reader.cs:line 177
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in D:\Working\IronyModManager\src\IronyModManager.Services\ModBaseService.cs:line 574
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in D:\Working\IronyModManager\src\IronyModManager.Services\ModService.cs:line 432
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in D:\Working\IronyModManager\src\IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 786
**Version:**
 - OS: [e.g. Windows]
 - Irony Version [e.g. 1.5.48]

**Additional context**

**Comment by bcssov** [comment]
Your mod files are located in OneDrive directory and Irony cannot reach them. Onedrive shutdown or not started perhaps, that is your problem not Irony.

**Comment by Timbletop** [comment]
i deleted all the files in the onedrive folder that was failing, problem was solved
