### ISSUE TITLE
IM Crash When resolving conflicts

### ISSUE THREAD

**Issue by Nanu308** [bcssov/IronyModManager#463]
**Describe the bug**
IM Crashes entirely.

**To Reproduce**
1. Resolve Conflicts Default
2. Resolve Conflicts in the Editor
3. Click Resolve
4. IM Crashes

**Expected behavior**
IM Not Crashing

**Screenshots**
![bilde](https://github.com/bcssov/IronyModManager/assets/59782240/c113d447-3071-42f9-8095-37ad9b023c30)

**Logs**
Unhandled error occurred. Please use this information to file a bug report:

```
2023-09-26 20:06:43.8738 Version: 1.25.121+8b72201300
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win10-x64
 RepoDb.Exceptions.MissingFieldsException: There are no database fields found for table 'playsets'. Make sure that the target table 'playsets' is present in the database and/or at least a single field is available.
   at RepoDb.DbFieldCache.ValidateDbFields(String tableName, DbFieldCollection dbFields)
   at RepoDb.DbFieldCache.GetAsyncInternal[TDbConnection](TDbConnection connection, String tableName, IDbTransaction transaction, Boolean enableValidation, CancellationToken cancellationToken)
   at RepoDb.CommandTextCache.GetTargetFieldsAsync(IDbConnection connection, String tableName, IEnumerable`1 fields, IDbTransaction transaction, CancellationToken cancellationToken)
   at RepoDb.CommandTextCache.GetQueryTextAsync(QueryRequest request, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.QueryAsyncInternalBase[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at RepoDb.DbConnectionExtension.QueryAsyncInternal[TEntity](IDbConnection connection, String tableName, QueryGroup where, IEnumerable`1 fields, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Nullable`1 cacheItemExpiration, Nullable`1 commandTimeout, String traceKey, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder, CancellationToken cancellationToken)
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.RecreateCollectionV2Async(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 875
   at IronyModManager.IO.Mods.Exporter.SQLiteExporter.ExportAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\Exporter\SQLiteExporter.cs:line 164
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass7_0.<<ApplyModsAsync>b__2>d.MoveNext() in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 113
--- End of stack trace from previous location ---
   at IronyModManager.IO.Mods.ModWriter.ApplyModsAsync(ModWriterParameters parameters) in D:\Working\IronyModManager\src\IronyModManager.IO\Mods\ModWriter.cs:line 116
```
**Version:**
 - OS: Windows 10 - 10.0.19045
 - Irony Version 1.25.121

**Additional context**
Non

**Comment by bcssov** [comment]
Delete sqlite file(s) from the documents\paradox interactive\stellaris it is corrupt.

**Comment by Nanu308** [comment]
> Delete sqlite file(s) from the documents\paradox interactive\stellaris it is corrupt.

That seems to have worked, thanks a lot 👍
