### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by JNeufeld5000** [bcssov/IronyModManager#480]
**Describe the bug**
Crash appears to be related to OneDrive attempting to backup files while Irony is attempting to parse the files. Please advise on how to avoid the crash.

**To Reproduce**
1. Irony crashes on start

**Expected behavior**
No crash

**Screenshots**

**Logs**
Unhandled error occurred. Please use this information to file a bug report:

2024-01-16 10:16:49.9110 Version: 1.25.155+9e32dc1236
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win10-x64
 System.IO.IOException: The cloud file provider is not running. : 'C:\Users\JN\OneDrive\OneDrive Documents\Paradox Interactive\Hearts of Iron IV\mod\ugc_2387530567.mod'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Read(Span`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadSpan(Span`1 destination, ArraySegment`1 arraySegment)
   at System.IO.Strategies.BufferedFileStreamStrategy.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at IronyModManager.IO.Readers.BaseSpecializedDiskReader.ReadInternal(String[] files, String path) in IronyModManager.IO\Readers\BaseSpecializedDiskReader.cs:line 153
   at IronyModManager.IO.Readers.BaseSpecializedDiskReader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in IronyModManager.IO\Readers\BaseSpecializedDiskReader.cs:line 132
   at IronyModManager.IO.Readers.Reader.Read(String path, IEnumerable`1 allowedPaths, Boolean searchSubFolders) in IronyModManager.IO\Readers\Reader.cs:line 177
   at IronyModManager.Services.ModBaseService.GetInstalledModsInternal(IGame game, Boolean ignorePatchMods) in IronyModManager.Services\ModBaseService.cs:line 584
   at IronyModManager.Services.ModService.InstallModsAsync(IEnumerable`1 statusToRetain) in IronyModManager.Services\ModService.cs:line 432
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.InstallModsAsync(Boolean skipOverlay) in IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 802

**Version:**
 - OS: Windows 10.0.19045
 - Irony Version 1.25.155

**Additional context**
I have OneDrive running on my machine. Sometimes it crashes, sometimes it does not. I'm attempting to diagnose when the crashes occur.

**Comment by bcssov** [comment]
It occurs when the OneDrive is not running as per the error message: The cloud file provider is not running.

It is recommended to not have your game files in the OneDrive as it frequently causes problems with the game itself. If Irony cannot reach the game files I doubt the game will too.

**Comment by JNeufeld5000** [comment]
Thanks!
