### ISSUE TITLE
Launcher experiencing Fatel unhandled Error

### ISSUE THREAD

**Issue by IkeaSteven** [bcssov/IronyModManager#482]
**Describe the bug**
The Launcher Crashes when trying to start the modded game.
Or after restart of the Launcher and adding Game executable manually. After 1-2 seconds of the launcher being started it Crashes.

**To Reproduce**
1. Have eu4.exe installed on C:/Programms(x86)/Europa Universalis 4
2. Add eu4.exe manually to Game executable and add mod "Ante Bellum"
3. Try to start modded version -> Unmodded version starts
4. Restart Irony wait 1-2 seconds -> Launcher crashes with Fatal error

**Expected behavior**
Modded version starts & Launcher not crashing without removing eu4.exe from Game executable after restart of launcher and stoppping of Eu4

**Screenshots**
![image](https://github.com/bcssov/IronyModManager/assets/157742793/f63476db-98ff-4b80-bc14-79794d389efb)
After Restart and starting the Game after manualy adding Game executable

![image](https://github.com/bcssov/IronyModManager/assets/157742793/54090b71-9f49-4901-ab17-cd6541488ce1)
Parallel to First start after adding Game exectuable

**Logs**
Error Log:
[localize.cpp:671]: Localization hash collision found, more info in text.log! Language: l_german
[localize.cpp:671]: Localization hash collision found, more info in text.log! Language: l_german

Log:/Fatal Error Log:
2024-01-26 00:17:11.7915 Version: 1.25.161+5094d15b6d
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: Invalid property identifier character: {. Path '', line 2, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 113
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in IronyModManager.Services\DLCService.cs:line 183
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnActivated>b__69_12() in IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 258
2024-01-26 00:42:22.2482 Version: 1.25.161+5094d15b6d
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: Invalid property identifier character: {. Path '', line 2, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 113
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in IronyModManager.Services\DLCService.cs:line 183
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnActivated>b__69_0() in IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 200
2024-01-26 00:42:42.8350 Version: 1.25.161+5094d15b6d
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win10-x64
 Newtonsoft.Json.JsonReaderException: Invalid property identifier character: {. Path '', line 2, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndAssert()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 113
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in IronyModManager.Services\DLCService.cs:line 183
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnActivated>b__69_0() in IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 200

**Version:**
 - OS: Windows 10 x64
 - Irony Version 1.25.161

**Additional context**
Laucher Stable after removing Game executable in between 1-2 seconds

**Comment by bcssov** [comment]
Just delete from documents folder dlc_load json. It's corrupt.
