### ISSUE TITLE
Can not start Irony Mod Manager after Update

### ISSUE THREAD

**Issue by Jruder1** [bcssov/IronyModManager#483]
**Describe the bug**
I can't apply my mods nor launch the game (CK3) after I updated Irony Mod Manager

**To Reproduce**
1. Launch Irony Mod Manager
2. Crash

**Expected behavior**
It crashes

**Logs**
Unhandled error occurred. Please use this information to file a bug report:

2024-01-26 14:10:45.0483 Version: 1.25.161+5094d15b6d
OS Description: Microsoft Windows 10.0.19042
Runtime Identifier: win10-x64
 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.AggregateException: Retry strategy failed. (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.) (Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90
   --- End of inner exception stack trace ---
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 105
   at IronyModManager.Services.ModBaseService.DeleteDescriptorsInternalAsync(IEnumerable`1 mods) in IronyModManager.Services\ModBaseService.cs:line 206
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.DeleteDescriptorAsync(IEnumerable`1 mods) in IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 734
   at IronyModManager.ViewModels.Controls.InstalledModsControlViewModel.<>c__DisplayClass227_0.<<OnActivated>b__13>d.MoveNext() in IronyModManager\ViewModels\Controls\InstalledModsControlViewModel.cs:line 953
 ---> (Inner Exception #1) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #2) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #3) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #4) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #5) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #6) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #7) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #8) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
 ---> (Inner Exception #9) System.UnauthorizedAccessException: Access to the path 'C:\Users\Josef.Ruderstam\Documents\Paradox Interactive\Crusader Kings III\mod\Debug.mod' is denied.
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at IronyModManager.IO.Common.DiskOperations.DeleteFile(String file) in IronyModManager.IO.Common\DiskOperations.cs:line 68
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>g__delete|0() in IronyModManager.IO\Mods\ModWriter.cs:line 217
   at IronyModManager.IO.Mods.ModWriter.<>c__DisplayClass11_0.<DeleteDescriptorAsync>b__1() in IronyModManager.IO\Mods\ModWriter.cs:line 223
   at IronyModManager.Shared.RetryStrategy.RetryActionAsync[T](Func`1 action) in IronyModManager.Shared\RetryStrategy.cs:line 90<---
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action)
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a)
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 73
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action)
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q)
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler)
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 217
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in IronyModManager\Program.cs:line 99
**Version:**
 - OS: [e.g. Windows]
 - Irony Version [e.g. 1.5.48]

**Comment by bcssov** [comment]
Your antivirus is kinda blocking irony from doing it's thing:
```
System.UnauthorizedAccessException:
```

**Comment by Jruder1** [comment]
Oh thank you Imma try to fix it
