### ISSUE TITLE
Failure to launch on OSX

### ISSUE THREAD

**Issue by LostHound** [bcssov/IronyModManager#497]
Hi team,

Want to report failure to launch on Mac OS - occurring with versions 1.26.145 and 1.26.146

On attempt to launch launch a Fatal Error occurs
The text of the error notification is below under Logs Section.

**To Reproduce**
1.  Follow run instructions
2. Start the app through Terminal (using command ./IronyModManager) or double-clicking the file in Finder (both produce the error).

**Screenshots**
<img width="688" alt="Screen Shot 2024-03-18 at 20 21 08" src="https://github.com/bcssov/IronyModManager/assets/163822760/e4b14177-70e1-4be0-85ae-6b70173f55df">

**Logs**

Unhandled error occurred. Please use this information to file a bug report:

2024-03-18 20:17:39.1344 Version: 1.26.145+d1f5601d43
OS Description: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64
Runtime Identifier: osx-x64
 System.ArgumentOutOfRangeException: The path '/var/folders/66/_xx59r6s6p53nmfn1qxf9b5c0000gn/T/CoreFxPipe_IronyModManager.3A7013501F4085B3FADB1E45DBE15769DFC281F5A8CC115B' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')
Actual value was /var/folders/66/_xx59r6s6p53nmfn1qxf9b5c0000gn/T/CoreFxPipe_IronyModManager.3A7013501F4085B3FADB1E45DBE15769DFC281F5A8CC115B.
   at System.Net.Sockets.UnixDomainSocketEndPoint..ctor(String path, String boundFileName)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer..ctor(String path, Int32 maxCount, Boolean isFirstPipeInstance)
   at System.IO.Pipes.NamedPipeServerStream.SharedServer.Get(String path, Int32 maxCount, PipeOptions pipeOptions)
   at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
   at IronyModManager.Implementation.SingleInstance.SingleInstance.Monitor() in IronyModManager\Implementation\SingleInstance\SingleInstance.cs:line 126
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Version:**
 - OS: Mac OS
 - Irony Version 1.26.46 and 1.26.145

**Comment by LostHound** [comment]
Rolling back to v1.25 launches fine

**Comment by bcssov** [comment]
I see the problem though official fix will have to wait, it's named pipe which ensures single instance that is being reported as too long. 

For the moment if you want to use 1.26 you can set this to false and it'll work:
https://github.com/bcssov/IronyModManager/blob/cfa4cb09dd7231bbfd8fe59e6e4d0a1cbdd93377/src/IronyModManager/appSettings.json#L45

**Comment by LostHound** [comment]
Thanks boss, that worked.
For anyone who struggles with that, just rolling back to v1.25.161 works (using Stellaris v3.11.2).
