### ISSUE TITLE
Fatal error 

### ISSUE THREAD

**Issue by Breadedchef** [bcssov/IronyModManager#515]
**Describe the bug**

**To Reproduce**
1. Install latest version of IronyModManager
2. Went through the installation process
3. ran the program 
4. 

**Expected behavior**
I expect to be able to run the program and have the ability to use it.  
**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.
Unhandled error occurred. Please use this information to file a bug report:

2024-08-09 07:03:26.8857 Version: 1.26.184+db628049e5
OS Description: Microsoft Windows 6.3.9600
Runtime Identifier: win-x64
 Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ,. Path 'enabled_mods[0]', line 2, position 18.
   at Newtonsoft.Json.JsonTextReader.ProcessValueComma()
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at IronyModManager.IO.Mods.Exporter.JsonExporter.LoadPdxModelAsync[T](String path) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 156
   at IronyModManager.IO.Mods.Exporter.JsonExporter.GetDisabledDLCAsync(DLCParameters parameters) in IronyModManager.IO\Mods\Exporter\JsonExporter.cs:line 113
   at IronyModManager.Services.DLCService.SyncStateAsync(IGame game, IReadOnlyCollection`1 dlc) in IronyModManager.Services\DLCService.cs:line 183
   at IronyModManager.ViewModels.Controls.DLCManagerControlViewModel.RefreshDLCAsync(IGame game) in IronyModManager\ViewModels\Controls\DLCManagerControlViewModel.cs:line 126
   at IronyModManager.ViewModels.Controls.ActionsControlViewModel.<OnActivated>b__69_0() in IronyModManager\ViewModels\Controls\ActionsControlViewModel.cs:line 200
**Version:**
 - OS: [e.g. Windows]
 - Irony Version [e.g. 1.5.48]

**Additional context**

**Comment by bcssov** [comment]
Delete dlc_load.json it is corrupt. This is a game file.
