### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ceforan** [bcssov/IronyModManager#527]
**Describe the bug**
Fatal exception occurred after updating to new IMM version upon attempting Default Without Localization Conflict Resolution.

Stellaris crashed about ~2 min past game load.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.
Unhandled error occurred. Please use this information to file a bug report:

2024-10-30 04:10:16.3300 Version: 1.26.197+766209568a
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win-x64
 ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at IronyModManager.Parser.ParametrizedParser.GetScriptPath(String parameters) in IronyModManager.Parser\ParametrizedParser.cs:line 91
   at IronyModManager.Services.ModPatchCollectionService.FindConflictsAsync(IIndexedDefinitions indexedDefinitions, IList`1 modOrder, PatchStateMode patchStateMode, IReadOnlyCollection`1 allowedLanguages) in IronyModManager.Services\ModPatchCollectionService.cs:line 472
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass195_0.<<AnalyzeModsAsync>b__3>d.MoveNext() in IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 664
--- End of stack trace from previous location ---
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.AnalyzeModsAsync(Int64 id, PatchStateMode mode, IEnumerable`1 versions) in IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 660
   at IronyModManager.ViewModels.Controls.ModHolderControlViewModel.<>c__DisplayClass200_0.<<OnActivated>g__runAnalysis|0>d.MoveNext() in IronyModManager\ViewModels\Controls\ModHolderControlViewModel.cs:line 855
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action)
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a)
   at Avalonia.Threading.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 73
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action)
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler)
   at Avalonia.Threading.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.Base/Threading/AvaloniaScheduler.cs:line 47
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 261
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at IronyModManager.Program.Main(String[] args) in IronyModManager\Program.cs:line 115

**Version:**
 - OS: [e.g. Windows]
 - Irony Version [e.g. 1.5.48]

**Additional context**

**Comment by ceforan** [comment]
any help would be appreciated.  I'm not quite up to snuff on diagnosing the issue myself.

**Comment by bcssov** [comment]
You can't fix it. A mod has something unexpected that fails and causes irony to crash. Try to narrow down the mod and let me know here I will take a look when I get home.

**Comment by ceforan** [comment]
ty, I think at least the problem with the game crashing was with Gigastructures.  I'll see if I can get more info on the mods.

**Comment by ceforan** [comment]
not been able yet, sorry

**Comment by kri32** [comment]
It happened with my local mod so I narrowed it down to tech files that have inlines in them. It was fixed after replacing the inlines with their content.

**Comment by bcssov** [comment]
Closing in favor of: #528 it has more details.
