### ISSUE TITLE
Vic3 - Mods with non-empty 'relationships' entry in metadata don't get parsed correctly

### ISSUE THREAD

**Issue by gfr-dev** [bcssov/IronyModManager#531]
**Describe the bug**
If a Vic3 mod has at least one entry under 'relationships', it will be displayed as an empty mod in the GUI. It can still be added/removed from collections, and the game will load the mod as normal.

**To Reproduce**
1. Subscribe to or create a mod with at least one item under 'relationships'.
2. Re-open Irony or check for new mods.
3. The mod will be displayed but won't have a title nor a supported version number.

**Expected behavior**
The mod should be displayed normally.

**Screenshots**
![image](https://github.com/user-attachments/assets/2f99d6da-fc6d-463f-abf8-5ed91fd974cc)

**Logs**
```
2024-12-22 21:52:50.6227 Version: 1.26.201+e13f58e91a
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win-x64
 System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.Parser.Mod.ModParser.ParseJsonMetadata(IEnumerable`1 lines) in IronyModManager.Parser\Mod\ModParser.cs:line 132
2024-12-22 21:52:50.6227 Version: 1.26.201+e13f58e91a
OS Description: Microsoft Windows 10.0.19045
Runtime Identifier: win-x64
 System.NullReferenceException: Object reference not set to an instance of an object.
   at IronyModManager.Parser.Mod.ModParser.ParseJsonMetadata(IEnumerable`1 lines) in IronyModManager.Parser\Mod\ModParser.cs:line 132
```

**Version:**
 - OS: Windows 10 22H2
 - Irony Version 1.26.201

**Additional context:**
Test mod metadata file:
```json
{
  "name" : "testmod",
  "id" : "test",
  "version" : "0.1.0",
  "supported_game_version" : "1.8.*",
  "short_description" : "Mod used for testing",
  "tags" : [],
  "relationships" : [
    {
      "rel_type" : "dependency",
      "id" : "com.github.Victoria-3-Modding-Co-op.Community-Mod-Framework",
      "display_name" : "Community Mod Framework",
      "resource_type" : "mod",
      "version" : "1.*"
    }
  ],
  "game_custom_data" : {
    "multiplayer_synchronized" : true
  }
}
```

**Comment by bcssov** [comment]
Looks like more complex relationships are now allowed, last time I checked I saw from examples that the field was a string array.
